<?php
// kate: encoding koi8-r
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'koi8-r';

// The php locale, LanguageCode_CountryCode
$l_locale= 'ru_RU';

$l_graphic_mode = "Графический режим";
$l_text_mode = "Текстовый режим";

// Logo
$l_back_kdevelop_home="обратно на начальную страницу";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Английский",
                   "ar" => "Арабский",
                   "cs" => "Чешский",
                   "de" => "Немецкий",
                   "es" => "Испанский",
                   "fr" => "Французский",
                   "hu" => "Венгерский",
                   "id" => "Индонезийский",
                   "it" => "Итальянский",
                   "nl" => "Голландский",
                   "pt" => "Португальский",
                   "pt_BR" => "Бразильский португальский",
                   "pl" => "Польский",
                   "ro" => "Румынский",
                   "ru" => "Русский",
                   "tr" => "Турецкий",
                   "uk" => "Украинский",
                   "zh_CN" => "Упрощенный китайский");

// Google module
$l_search="Поиск";

// Quick download module
$l_quick_downloads = "Быстрая загрузка";
$l_current_stable_version = "Текущая стабильная версия";
$l_current_development_version = "Версия в разработке";

// Menu module
$l_website_navigation="Навигация по сайту";
$l_all_versions="все&nbsp;версии";
$l_general="Общее";
$l_home="Главная страница";
$l_versions="Версии";
$l_features="Возможности";
$l_requirements="Требования";
$l_download="Загрузка";
$l_cvs_branches_compiling="Ветки SVN и компиляция";
$l_changes="Изменения";
$l_bugs_wishes="Ошибки и пожелания";

$l_documentation="Документация";
$l_user_manual="Руководство пользователя";
$l_api_documentation="Руководство по API";
$l_platform_api_documentation="Platform API";
$l_tutorials="Учебные пособия";
$l_faq="Вопросы и ответы";
$l_technotes="TechNotes";
$l_mediawiki="Wiki";

$l_presentations_graphics="Графика и презентации";
$l_screenshots="Снимки экрана";
$l_in_the_press="Публикации";
$l_awards="Награды";
$l_logos_banners="Логотипы и баннеры";
$l_splashscreens="Заставки";
$l_events="События";

$l_development="Разработка";
$l_join_us="Присоединяйтесь к нам!";
$l_current_work_todo_list="Текущая работа, список TODO";
$l_latest_cvs_commits="Последние изменения в SVN";
$l_browse_code="Просмотр кода";
$l_web_cvs="Web SVN";
$l_gui_translation="Перевод интерфейса";
$l_user_manual_translation="Перевод руководства";
$l_website_translation="Перевод сайта";
$l_upload="Загрузка файлов";

$l_links="Ссылки";
$l_user_progs="Программы";
$l_sponsors="Спонсоры";
$l_donation="Пожертвования";
$l_development_tools="Средства разработки";

$l_contacts="Контакты";
$l_on_line_chat="IRC чат";
$l_forum="Форум";
$l_mailinglist="Список рассылки";
$l_guestbook="Гостевая книга";
$l_credits="Авторы";

$l_misc="Разное";
$l_license="Лицензия";
$l_sitemap="Карта сайта";

// Stats module
$l_user_online = "посетителей на сайте";
$l_visitors_since = "посетителей с 22.09.1998";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Обсуждение</a> KDevelop, <a href=\"http://www.kde.org/\">KDE</a>, <a href=\"http://www.trolltech.com\">Qt</a> и других вопросов.";

// IRC module
$l_irc_description="Встретить других пользователей и разработчикоа можно на канале <a href=\"chat/\"><em>#kdevelop</em> на сервере <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Снимки экрана";
$l_picture_corner_description="KDevelop 3.0 в режиме IDEAl используя KDE 3.2 с темой Plastik";

// User Programs module
$l_total = "всего:";
$l_newest_entries = "новых <b>%s</b>";
$l_by = " - ";

// Downloads Per Hour module
$l_downloads_per_hour = "Количество загрузок в час";

// ChangeLog module
$l_change_log = "Список изменений";


// Content module
$l_page_is_outdated = "<b>Эта страница содержит устаревшую информацию</b>. <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">Доступна более новая страница на английском языке</a>";
$l_translation_by = "Сайт перевели и переводят: ";
$l_last_updated = "Эта страница была обновлена: ";
$l_website_bugs = "В случае проблем с сайтом, свяжитесь с ";


// "Other versions" links
$l_other_versions="Другие версии";
$l_other_news="Другие новости";
$l_branches_compiling_section_at="Раздел компиляции на странице";
$l_bugs_section_at="Раздел ошибок и пожеланий на странице";
$l_download_section_at="Раздел загрузки на странице";
$l_requirements_section_at="Раздел требований на странице";
$l_tutorials_section_at="Раздел учебных пособий на странице";


// Page titles
$l_pt_main="интегрированная среда разработки - Главная страница";
$l_pt_main_year="Новости %d г.";
$l_pt_versions="Выпущенные версии";
$l_pt_in_the_press="В прессе";
$l_pt_license="Лицензия";
$l_pt_donate="Пожертвования и спонсорство";
$l_pt_website_translation_status="Состояние перевода сайта";
$l_pt_optional_files_translation_status="Состояние перевода сайта (необязательные файлы)";
$l_pt_sitemap="Карта сайта";
$l_pt_upload="Загрузка файлов";
$l_pt_current_work="Текущая работа";
$l_pt_join_the_team="Присоединяйтесь к нам!";
$l_pt_awards="Награды";
$l_pt_logos_banners="Логотипы и баннеры";
$l_pt_pic_corner="Снимки экрана";
$l_pt_splashscreens="Заставки";
$l_pt_users="Программы";
$l_pt_sponsors="Спонсоры";
$l_pt_links_development="Ссылки разработчику";
$l_pt_links_tools="Средства разработки";
$l_pt_mailinglist="Списки рассылки";
$l_pt_bugs="Ошибки и пожелания";
$l_pt_stats="Статистика сайта";
$l_pt_doc_technotes_index="Каталог TechNotes";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Архивы гостевой книги";
$l_pt_guestbook_guestbook_010203_1999="Гостевая книга январь, февраль, март 1999 г.";
$l_pt_guestbook_guestbook_040506_1999="Гостевая книга апрель, май, июнь 1999 г.";
$l_pt_guestbook_guestbook_0708_1999="Гостевая книга июль, август 1999 г.";
$l_pt_guestbook_guestbook_091011_1999="Гостевая книга сентябрь, октябрь, ноябрь 1999 г.";
$l_pt_guestbook_guestbook_12_03_1999_2000="Гостевая книга декабрь, январь, февраль, март 1999/2000 гг.";
$l_pt_guestbook_guestbook_2000_2004="Гостевая книга апрель 2000 г. - июль 2004 г.";
$l_pt_events="События";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x Главная страница";
$l_pt_1_3_announce_kdevelop_1_3="1.3 Аннонс выпуска";
$l_pt_1_3_authors="1.x Авторы";
$l_pt_1_3_changes="1.x Изменения";
$l_pt_1_3_features="1.x Возможности";
$l_pt_1_3_pressrelease1_0="1.0 Пресс-релиз";
$l_pt_1_3_pressrelease1_1="1.1 Пресс-релиз";
$l_pt_1_3_screenshots1="1.x Снимки экрана раздел 1";
$l_pt_1_3_screenshots2="1.x Снимки экрана раздел 2";
$l_pt_1_3_screenshots3="1.x Снимки экрана раздел 3";
$l_pt_2_1_kdevelop="2.x Главная страница";
$l_pt_2_1_announce_kdevelop_2_0="2.0 Аннонс выпуска";
$l_pt_2_1_authors="2.x Авторы";
$l_pt_2_1_changes="2.x Изменения";
$l_pt_2_1_faq="2.x Вопросы и ответы";
$l_pt_2_1_features="2.x Возможности";
$l_pt_2_1_screenshots1="2.x Снимки экрана раздел 1";
$l_pt_2_1_screenshots2="2.x Снимки экрана раздел 2";
$l_pt_2_1_screenshots3="2.x Снимки экрана раздел 3";
$l_pt_x_x_kdevelop="%s.x Главная страница";
$l_pt_x_x_announce_kdevelop="%s Аннонс выпуска";
$l_pt_x_x_authors="%s.x Авторы";
$l_pt_x_x_branches_compiling="%s.x Ветки SVN и компиляция";
$l_pt_x_x_changes="%s.x Изменения";
$l_pt_x_x_faq="%s.x Вопросы и ответы";
$l_pt_x_x_download="%s.x Загрузка";
$l_pt_x_x_features="%s.x Возможности";
$l_pt_x_x_kdevelop_po_status="%s.x Состояние перевода интерфейса";
$l_pt_x_x_requirements="%s.x Требования";
$l_pt_x_x_screenshots="%s.x Снимки экрана";
$l_pt_x_x_screenshots1="%s.x Снимки экрана раздел 1";
$l_pt_x_x_screenshots2="%s.x Снимки экрана раздел 2";
$l_pt_x_x_screenshots3="%s.x Снимки экрана раздел 3";
$l_pt_x_x_tutorials="%s.x Учебные пособия";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Использование Autoconf/Automake";
$l_pt_x_x_doc_kmditutorial_index="%s.x Руководство по KMDI";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Руководство по Qtopia";
$l_pt_x_x_doc_tutorial_settings_index="%s.x Использование пользовательских настроек";
$l_pt_x_x_ChangeLog="%s.x Журнал изменений SVN";
$l_pt_HEAD_kdevelop="HEAD Главная страница";
$l_pt_HEAD_authors="HEAD Авторы";
$l_pt_HEAD_branches_compiling="HEAD Ветки SVN и компиляция";
$l_pt_HEAD_changes="HEAD Изменения";
$l_pt_HEAD_ChangeLog="HEAD Журнал изменений SVN";
$l_pt_HEAD_faq="HEAD Вопросы и ответы";
$l_pt_HEAD_download="HEAD Загрузка";
$l_pt_HEAD_features="HEAD Возможности";
$l_pt_HEAD_kdevelop_po_status="HEAD Состояние перевода интерфейса";
$l_pt_HEAD_requirements="HEAD Требования";
$l_pt_HEAD_screenshots="HEAD Снимки экрана";
$l_pt_HEAD_screenshots1="HEAD Снимки экрана раздел 1";
$l_pt_HEAD_screenshots2="HEAD Снимки экрана раздел 2";
$l_pt_HEAD_screenshots3="HEAD Снимки экрана раздел 3";
$l_pt_tutorials="Учебные пособия";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/ru/kdevelop/kdevelop/';
