<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'pl_PL';

$l_graphic_mode = "Tryb Graficzny";
$l_text_mode = "Tryb Tekstowy";

// Logo
$l_back_kdevelop_home="powrót do strony domowej KDevelop";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Angielski",
                   "ar" => "Arabic",
                   "cs" => "Czeski",
                   "de" => "Niemiecki",
                   "es" => "Hiszpański",
                   "fr" => "Francuski",
                   "hu" => "Węgierski",
                   "id" => "Indonezyjski",
                   "it" => "Włoski",
                   "nl" => "Holenderski",
                   "pt" => "Portugalski",
                   "pt_BR" => "Brazylijski Portugalski",
                   "pl" => "Polski",
                   "ro" => "Rumuński",
                   "ru" => "Rosyjski",
                   "tr" => "Turecki",
                   "uk" => "Ukraiński",
                   "zh_CN" => "Uproszczony Chiński");

// Google module
$l_search="Szukaj";

// Quick download module
$l_quick_downloads = "Szybkie pobieranie";
$l_current_stable_version = "Obecna wersja stabilna";
$l_current_development_version = "Obecna wersja rozwojowa";

// Menu module
$l_website_navigation="Nawigacja serwisu";
$l_all_versions="wszystkie&nbsp;wersje";
$l_general="Główne";
$l_home="Strona główna";
$l_versions="Wersje";
$l_features="Cechy";
$l_requirements="Wymagania";
$l_download="Pobieranie";
$l_cvs_branches_compiling="Gałęzie SVN<br>i kompilacja";
$l_changes="Zmiany";
$l_bugs_wishes="Błędy i życzenia";

$l_documentation="Dokumentacja";
$l_user_manual="Podręcznik użytkownika";
$l_api_documentation="Dokumentacja API";
$l_platform_api_documentation="API platformy";
$l_tutorials="Przewodniki";
$l_faq="F.A.Q.";
$l_technotes="Notatki techniczne";
$l_mediawiki="Wiki";

$l_presentations_graphics="Prezentacje graficzne";
$l_screenshots="Zrzuty ekranu";
$l_in_the_press="W prasie";
$l_awards="Nagrody";
$l_logos_banners="Loga i banery";
$l_splashscreens="Splashscreeny";
$l_events="Wydarzenia";

$l_development="Rozwój";
$l_join_us="Dołacz do nas!";
$l_current_work_todo_list="Obecne prace,<br>lista TODO";
$l_latest_cvs_commits="Ostatnie zgłoszenia SVN";
$l_browse_code="Przeglądaj kod";
$l_web_cvs="SVN przez WWW";
$l_gui_translation="Tłumaczenia GUI";
$l_user_manual_translation="Tłumaczenia podręcznika użytkownika";
$l_website_translation="Tłumaczenie serwisu";
$l_upload="Wrzuć plik";

$l_links="Linki";
$l_user_progs="Programy użytkowników";
$l_sponsors="Sponsorzy";
$l_donation="Dotacje";
$l_development_tools="Narzędzia programistyczne";

$l_contacts="Kontakt";
$l_on_line_chat="Chat online";
$l_forum="Forum";
$l_mailinglist="Listy Mailingowe";
$l_guestbook="Księga gości";
$l_credits="Podziękowania";

$l_misc="Różne";
$l_license="Licencja";
$l_sitemap="Mapa serwisu";

// Stats module
$l_user_online = "Użytkowników online";
$l_visitors_since = "Odwiedzających od 09/22/98";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Forum</a> dla KDevelop, <a href=\"http://www.kde.org/\">KDE</a> i innymi powiązanymi z <a href=\"http://www.trolltech.com\">Qt</a>.";

// IRC module
$l_irc_description="Możesz poznać innych użytkowników i deweloperów na kanale <a href=\"chat/\"><em>#kdevelop</em> w <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Kącik obrazków";
$l_picture_corner_description="KDevelop 3.0 w trybie IDEAl używając KDE 3.2 z tematem Plastik";

// User Programs module
$l_total = "ogółem:";
$l_newest_entries = "najnowsze wpisy <b>%s</b>";
$l_by = "przez";

// Downloads per hour
$l_downloads_per_hour = "Pobrań na godzinę";

// ChangeLog module
$l_change_log = "Protokół zmian";

// Content module
$l_page_is_outdated = "<b>Ta strona jest przeterminowana</b>, istnieje nowsza <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">angielska wersja</a> strony";
$l_translation_by = "Polskie tłumaczenie projektu prowadzone przez ";
$l_last_updated = "Ta strona była ostatnio aktualizowana: ";
$l_website_bugs = "Osoba odpowiedzialna w przypadku wystąpienia błędu na stronie to: ";

// "Other versions" links
$l_other_versions="Inne wersje";
$l_other_news="Inne newsy";
$l_branches_compiling_section_at="Sekcja kompilowania na";
$l_bugs_section_at="Sekcja błędów i życzeń na";
$l_download_section_at="Sekcja pobierania na";
$l_requirements_section_at="Sekcja wymagań na";
$l_tutorials_section_at="Sekcja przewodników na";

// Page titles
$l_pt_main="Strona domowa Integrated Development Environment";
$l_pt_main_year="Newsy %d";
$l_pt_versions="Wydane wersje";
$l_pt_in_the_press="W prasie";
$l_pt_license="Licencja";
$l_pt_donate="Dotacje i Sponsoring";
$l_pt_website_translation_status="Status tłumaczenia serwisu";
$l_pt_optional_files_translation_status="Status tłumaczenia serwisu (opcjonalne pliki)";
$l_pt_sitemap="Mapa serwisu";
$l_pt_upload="Wrzuć plik";
$l_pt_current_work="Obecna praca";
$l_pt_join_the_team="Dołącz do nas!";
$l_pt_awards="Nagrody";
$l_pt_logos_banners="Loga i Banery";
$l_pt_pic_corner="Archiwum kącika obrazków";
$l_pt_splashscreens="Splashscreeny";
$l_pt_users="Programy użytkowników";
$l_pt_sponsors="Sponsorzy";
$l_pt_links_development="Linki dla deweloperów";
$l_pt_links_tools="Narzędzia dla deweloperów";
$l_pt_mailinglist="Listy mailingowe";
$l_pt_bugs="Błędy i życzenia";
$l_pt_stats="Statystyki serwisu";
$l_pt_doc_technotes_index="Index notatek technicznych";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Archiwum Księgi Gości";
$l_pt_guestbook_guestbook_010203_1999="Księga Gości Sty/Lut/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Księga Gości Kwi/Maj/Cze 1999";
$l_pt_guestbook_guestbook_0708_1999="Księga Gości Lip/Sie 1999";
$l_pt_guestbook_guestbook_091011_1999="Księga Gości Wrz/Paź/Lis 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Księga Gości Gru/Sty/Lut/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Księga Gości Kwi 2000 / Lip 2004";
$l_pt_events="wydarzenia";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="Strona główna wydania 1.x";
$l_pt_1_3_announce_kdevelop_1_3="Informacje o wydaniu 1.3";
$l_pt_1_3_authors="Autorzy wydania 1.x";
$l_pt_1_3_changes="Zmiany w wydaniu 1.x";
$l_pt_1_3_features="Cechy wydania 1.x";
$l_pt_1_3_pressrelease1_0="Wydanie prasowe 1.0";
$l_pt_1_3_pressrelease1_1="Wydanie prasowe 1.1";
$l_pt_1_3_screenshots1="Sekcja zrzutów ekranu wydania 1.x 1";
$l_pt_1_3_screenshots2="Sekcja zrzutów ekranu wydania 1.x 2";
$l_pt_1_3_screenshots3="Sekcja zrzutów ekranu wydania 1.x 3";
$l_pt_2_1_kdevelop="Strona główna wydania 2.x";
$l_pt_2_1_announce_kdevelop_2_0="Informacje o wydaniu 2.0";
$l_pt_2_1_authors="Autorzy wydania 2.x";
$l_pt_2_1_changes="Zmiany w wydaniu 2.x";
$l_pt_2_1_faq="FAQ wydania 2.x";
$l_pt_2_1_features="Cechy wydania 2.x";
$l_pt_2_1_screenshots1="Sekcja zrzutów ekranu wydania 2.x 1";
$l_pt_2_1_screenshots2="Sekcja zrzutów ekranu wydania 2.x 2";
$l_pt_2_1_screenshots3="Sekcja zrzutów ekranu wydania 2.x 3";
$l_pt_x_x_kdevelop="Strona główna wydania %s.x";
$l_pt_x_x_announce_kdevelop="Informacje o wydaniu %s";
$l_pt_x_x_authors="Autorzy wydania %s.x";
$l_pt_x_x_branches_compiling="Gałęzie SVN wydania %s.x i kompilacja";
$l_pt_x_x_changes="Zmiany w wydaniu %s.x";
$l_pt_x_x_faq="FAQ wydania %s.x";
$l_pt_x_x_download="Dział pobierania wydania %s.x";
$l_pt_x_x_features="Cechy wydania %s.x";
$l_pt_x_x_kdevelop_po_status="Status tłumaczenia GUI wydania %s.x";
$l_pt_x_x_requirements="Wymagania wydania %s.x";
$l_pt_x_x_screenshots="Sekcja zrzutów ekranu wydania %s.x";
$l_pt_x_x_screenshots1="Sekcja zrzutów ekranu wydania %s.x 1";
$l_pt_x_x_screenshots2="Sekcja zrzutów ekranu wydania %s.x 2";
$l_pt_x_x_screenshots3="Sekcja zrzutów ekranu wydania %s.x 3";
$l_pt_x_x_tutorials="Przewodniki wydania %s.x";
$l_pt_x_x_doc_tutorial_autoconf="Przewodnik wydania %s.x dla Autoconf/Automake"; 
$l_pt_x_x_doc_kmditutorial_index="Przewodnik wydania %s.x dla KMDI";
$l_pt_x_x_doc_tutorial_qtopia_index="Przewodnik wydania %s.x dla Qtopia";
$l_pt_x_x_doc_tutorial_settings_index="Przewodnik wydania %s.x dla \"Ustawień zdefiniowanych przez użytkownika\"";
$l_pt_x_x_ChangeLog="Indywidualne logi zgłoszeń SVN dla wydania %s.x";
$l_pt_HEAD_kdevelop="Strona główna wydania HEAD";
$l_pt_HEAD_authors="Autorzy wydania HEAD";
$l_pt_HEAD_branches_compiling="Gałęzie SVN wydania HEAD i kompilacja";
$l_pt_HEAD_changes="Zmiany w wydaniu HEAD";
$l_pt_HEAD_ChangeLog="Indywidualne logi zgłoszeń SVN dla wydania HEAD";
$l_pt_HEAD_faq="FAQ wydania HEAD";
$l_pt_HEAD_download="Pobiernie wydania HEAD";
$l_pt_HEAD_features="Cechy wydania HEAD";
$l_pt_HEAD_kdevelop_po_status="Status tłumaczenia GUI wydania HEAD";
$l_pt_HEAD_requirements="Wymagania wydania HEAD";
$l_pt_HEAD_screenshots="Sekcja zrzutów ekranu wydania HEAD";
$l_pt_HEAD_screenshots1="Sekcja zrzutów ekranu wydania HEAD 1";
$l_pt_HEAD_screenshots2="Sekcja zrzutów ekranu wydania HEAD 2";
$l_pt_HEAD_screenshots3="Sekcja zrzutów ekranu wydania HEAD 3";
$l_pt_tutorials="Przewodniki";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
