<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'fr_FR';

$l_graphic_mode = "Mode graphique";
$l_text_mode = "Mode texte";

// Logo
$l_back_kdevelop_home="retour &agrave; la page principale de KDevelop";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Anglais",
                   "ar" => "Arabic",
                   "cs" => "Tch&egrave;que",
                   "de" => "Allemand",
                   "es" => "Espagnol",
                   "fr" => "Fran&ccedil;ais",
                   "hu" => "Hungarian",
                   "id" => "Indon&eacute;sien",
                   "it" => "Italien",
                   "nl" => "Hollandais",
                   "pt" => "Portugais",
                   "pt_BR" => "Br&eacute;silien Portugais",
                   "pl" => "Polonais",
                   "ro" => "Roumain",
                   "ru" => "Russe",
                   "tr" => "Turc",
                   "uk" => "Ukranien",
                   "zh_CN" => "Chinois Simplifi&eacute;");

// Google module
$l_search="Recherche";

// Quick downloads module
$l_quick_downloads = "T&eacute;l&eacute;chargement rapide";
$l_current_stable_version = "Version stable actuelle";
$l_current_development_version = "Version de d&eacute;veloppement actuelle";

// Menu module
$l_website_navigation="Contenu du site web";
$l_all_versions="Toutes&nbsp;les versions";
$l_general="G&eacute;n&eacute;ral";
$l_home="Page principale";
$l_versions="Versions";
$l_features="Caract&eacute;ristiques";
$l_requirements="Conditions requises";
$l_download="T&eacute;l&eacute;chargement";
$l_cvs_branches_compiling="Branches SVN &amp; Compilation";
$l_changes="Changements";
$l_bugs_wishes="Bogues &amp; souhaits";

$l_documentation="Documentation";
$l_user_manual="Manuel de l&#039;utilisateur";
$l_api_documentation="Docs API";
$l_platform_api_documentation="Platform API";
$l_tutorials="Tutoriels";
$l_faq="Foire aux questions (F.A.Q.)";
$l_technotes="Notes techniques";
$l_mediawiki="Wiki";

$l_presentations_graphics="Pr&eacute;sentations et graphiques";
$l_screenshots="Captures d&#039;&eacute;cran";
$l_in_the_press="Dans la presse";
$l_awards="R&eacute;compenses";
$l_logos_banners="Logos &amp; banni&egrave;res";
$l_splashscreens="Images de d&eacute;marrage";
$l_events="&Eacute;v&eacute;nements";

$l_development="D&eacute;veloppement";
$l_join_us="Rejoignez-nous !";
$l_current_work_todo_list="Travail en cours, liste &agrave; faire";
$l_latest_cvs_commits="Derniers commits au SVN";
$l_browse_code="Naviguer dans le code";
$l_web_cvs="SVN Web";
$l_gui_translation="Traduction de l&#039;interface";
$l_user_manual_translation="Traduction du manuel de l&#039;utilisateur";
$l_website_translation="Traduction du site Web";
$l_upload="Envoi";

$l_links="Liens";
$l_user_progs="Progs. des utilisateurs";
$l_sponsors="Sponsors";
$l_donation="Dons";
$l_development_tools="Outils de d&eacute;v.";

$l_contacts="Contacts";
$l_on_line_chat="Discussion en ligne";
$l_forum="Forum";
$l_mailinglist="Liste de discussion";
$l_guestbook="Livre d&#039;or";
$l_credits="Remerciements";

$l_misc="Divers";
$l_license="Licence";
$l_sitemap="Plan du site";

// Stats module
$l_user_online = "Utilisateurs en ligne";
$l_visitors_since = "Visiteurs depuis le 22/09/98";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Panneau</a> de discussion pour les sujets relatifs &agrave; KDevelop, <a href=\"http://www.kde.org/\">KDE</a> et <a href=\"http://www.trolltech.com\">Qt</a>.";

// IRC module
$l_irc_description="Vous pouvez rencontrer d&#039;autres utilisateurs et d&eacute;veloppeurs sur le <a href=\"chat/\">canal <em>#kdevelop</em> sur <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Coin des images";
$l_picture_corner_description="KDevelop 3.0 en mode IDEAl sous KDE 3.2 avec le th&egrave;me Plastik";

// User Programs module
$l_total = "total :";
$l_newest_entries = "Les <b>%s</b> entr&eacute;es les plus r&eacute;centes";
$l_by = "par";

// Downloads Per Hour module
$l_downloads_per_hour = "T&eacute;l&eacute;chargements par heure";

// ChangeLog module
$l_change_log = "Historique";

// Content module
$l_page_is_outdated = "<b>Cette page n&#039;est pas &agrave; jour</b>, une nouvelle <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">version en anglais</a> existe";
$l_translation_by = "Traduction fran&ccedil;aise maintenue par ";
$l_last_updated = "Cette page a &eacute;t&eacute; mise &agrave; jour pour la derni&egrave;re fois le : ";
$l_website_bugs = "Pour tout probl&egrave;me avec le site web, merci de contacter le ";

// "Other versions" links
$l_other_versions="Autres versions";
$l_other_news="Autres nouvelles";
$l_branches_compiling_section_at="Section de compilation sur";
$l_bugs_section_at="Section bogues &amp; souhaits sur";
$l_download_section_at="Section t&eacute;l&eacute;chargements sur";
$l_requirements_section_at="Section conditions requises sur";
$l_tutorials_section_at="Section tutoriels sur";

// Page titles
$l_pt_main="Un environnement de d&eacute;veloppement int&eacute;gr&eacute; - Page d&#039;accueil";
$l_pt_main_year="Nouvelles de %d";
$l_pt_versions="Versions sorties";
$l_pt_in_the_press="Dans la presse";
$l_pt_license="Licence";
$l_pt_donate="Sponsors et dons";
$l_pt_website_translation_status="&Eacute;tat de la traduction du site";
$l_pt_optional_files_translation_status="&Eacute;tat de la traduction du site (fichiers optionels)";
$l_pt_sitemap="Plan du site (sitemap)";
$l_pt_upload="Envoi";
$l_pt_current_work="Travail en cours";
$l_pt_join_the_team="Rejoignez-nous !";
$l_pt_awards="R&eacute;compenses";
$l_pt_logos_banners="Logos &amp; banni&egrave;res";
$l_pt_pic_corner="Archive du coin des images";
$l_pt_splashscreens="&Eacute;crans de d&eacute;marrage";
$l_pt_users="Programmes des utilisateurs";
$l_pt_sponsors="Sponsors";
$l_pt_links_development="Liens de d&eacute;veloppement";
$l_pt_links_tools="Outils de d&eacute;veloppement";
$l_pt_mailinglist="Liste de discussion";
$l_pt_bugs="Bogues &amp; souhaits";
$l_pt_stats="Statistiques du site web";
$l_pt_doc_technotes_index="Index des notes techniques";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Archives du livre d&#039;or";
$l_pt_guestbook_guestbook_010203_1999="Livre d&#039;or Jan/F&eacute;v/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Livre d&#039;or Avr/Mai/Juin 1999";
$l_pt_guestbook_guestbook_0708_1999="Livre d&#039;or Juil/Ao&ucirc;t 1999";
$l_pt_guestbook_guestbook_091011_1999="Livre d&#039;or Sep/Oct/Nov 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Livre d&#039;or Dec/Jan/F&eacute;v/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Livre d&#039;or Avr 2000 / Juil 2004";
$l_pt_events="&Eacute;v&eacute;nements";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="Info princ. 1.x";
$l_pt_1_3_announce_kdevelop_1_3="Annonce de sortie de la version 1.3";
$l_pt_1_3_authors="Auteurs 1.x";
$l_pt_1_3_changes="Changements 1.x";
$l_pt_1_3_features="Caract&eacute;ristiques 1.x";
$l_pt_1_3_pressrelease1_0="Communiqu&eacute; de presse 1.0";
$l_pt_1_3_pressrelease1_1="Communiqu&eacute; de presse 1.1";
$l_pt_1_3_screenshots1="Captures d&#039;&eacute;cran 1.x page 1";
$l_pt_1_3_screenshots2="Captures d&#039;&eacute;cran 1.x page 2";
$l_pt_1_3_screenshots3="Captures d&#039;&eacute;cran 1.x page 3";
$l_pt_2_1_kdevelop="Info princ. 2.x";
$l_pt_2_1_announce_kdevelop_2_0="Annonce de sortie de la version 2.0";
$l_pt_2_1_authors="Auteurs 2.x";
$l_pt_2_1_changes="Changements 2.x";
$l_pt_2_1_faq="Foire aux questions 2.x";
$l_pt_2_1_features="caract&eacute;ristiques 2.x";
$l_pt_2_1_screenshots1="Captures d&#039;&eacute;cran 2.x page 1";
$l_pt_2_1_screenshots2="Captures d&#039;&eacute;cran 2.x page 2";
$l_pt_2_1_screenshots3="Captures d&#039;&eacute;cran 2.x page 3";
$l_pt_x_x_kdevelop="Info princ. %s.x";
$l_pt_x_x_announce_kdevelop="Annonce de sortie de la version %s";
$l_pt_x_x_authors="Auteurs %s.x";
$l_pt_x_x_branches_compiling="Branches SVN &amp; compilation %s.x ";
$l_pt_x_x_changes="Changements %s.x";
$l_pt_x_x_faq="Foire aux questions %s.x";
$l_pt_x_x_download="T&eacute;l&eacute;chargements %s.x";
$l_pt_x_x_features="Caract&eacute;ristiques %s.x";
$l_pt_x_x_kdevelop_po_status="&Eacute;tat de la traduction de l&#039;interface %s.x";
$l_pt_x_x_requirements="Conditions requises %s.x";
$l_pt_x_x_screenshots="Captures d&#039;&eacute;cran %s.x";
$l_pt_x_x_screenshots1="Captures d&#039;&eacute;cran %s.x page 1";
$l_pt_x_x_screenshots2="Captures d&#039;&eacute;cran %s.x page 2";
$l_pt_x_x_screenshots3="Captures d&#039;&eacute;cran %s.x page 3";
$l_pt_x_x_tutorials="Tutoriels %s.x";
$l_pt_x_x_doc_tutorial_autoconf="Tutoriel %s.x pour Autoconf/Automake"; 
$l_pt_x_x_doc_kmditutorial_index="Tutoriel %s.x KMDIl";
$l_pt_x_x_doc_tutorial_qtopia_index="Tutoriel %s.x Qtopia";
$l_pt_x_x_doc_tutorial_settings_index="Tutoriel %s.x \"Configuration par l'utilisateur\"";
$l_pt_x_x_ChangeLog="Journaux des changements svn %s.x individuels";
$l_pt_HEAD_kdevelop="Info princ. HEAD";
$l_pt_HEAD_authors="Auteurs HEAD";
$l_pt_HEAD_branches_compiling="Branches SVN &amp; compilation HEAD";
$l_pt_HEAD_changes="Changements HEAD";
$l_pt_HEAD_ChangeLog="Journaux des changements SVN HEAD individuels";
$l_pt_HEAD_faq="Foire aux questions HEAD";
$l_pt_HEAD_download="T&eacute;l&eacute;chargements HEAD";
$l_pt_HEAD_features="Caract&eacute;ristiques HEAD";
$l_pt_HEAD_kdevelop_po_status="&Eacute;tat de la traduction de l&#039;interface HEAD";
$l_pt_HEAD_requirements="Conditions requises HEAD";
$l_pt_HEAD_screenshots="Captures d&#039;&eacute;cran HEAD";
$l_pt_HEAD_screenshots1="Captures d&#039;&eacute;cran HEAD page 1";
$l_pt_HEAD_screenshots2="Captures d&#039;&eacute;cran HEAD page 2";
$l_pt_HEAD_screenshots3="Captures d&#039;&eacute;cran HEAD page 3";
$l_pt_tutorials="Tutoriels";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
