<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'cs_CZ';

$l_graphic_mode = "Grafický mód";
$l_text_mode = "Textový mód";

// Logo
$l_back_kdevelop_home="zpět na domovskou stránku KDevelop";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Angličtina",
                   "ar" => "Arabic",
                   "cs" => "Čeština",
                   "de" => "Němčina",
                   "es" => "Španělština",
                   "fr" => "Francouzština",
                   "hu" => "Hungarian",
                   "id" => "Indonéština",
                   "it" => "Italština",
                   "nl" => "Holandština",
                   "pt" => "Portugalština",
                   "pt_BR" => "Brazilská portugalština",
                   "pl" => "Polština",
                   "ro" => "Rumunština",
                   "ru" => "Ruština",
                   "tr" => "Turečtina",
                   "uk" => "Ukrajinština",
                   "zh_CN" => "Zjednodušená čínština");

// Google module
$l_search="Vyhledávání";

// Quick download module
$l_quick_downloads = "Rychlé stažení";
$l_current_stable_version = "Aktuální stabilní verze";
$l_current_development_version = "Aktuální vývojová verze";

// Menu module
$l_website_navigation="Navigace";
$l_all_versions="všechny&nbsp;verze";
$l_general="Hlavní";
$l_home="Hlavní stránka";
$l_versions="Verze";
$l_features="Vlastnosti";
$l_requirements="Požadavky";
$l_download="Download";
$l_cvs_branches_compiling="SVN větve &amp; kompilace";
$l_changes="Změny";
$l_bugs_wishes="Chyby &amp; přání";

$l_documentation="Dokumentace";
$l_user_manual="Uživatelský manuál";
$l_api_documentation="API dokumentace";
$l_platform_api_documentation="Platform API";
$l_tutorials="Návody";
$l_faq="F.A.Q.";
$l_technotes="Tech. poznámky";
$l_mediawiki="Wiki";

$l_presentations_graphics="Prezentace a grafika";
$l_screenshots="Snímky obrazovek";
$l_in_the_press="V tisku";
$l_awards="Ocenění";
$l_logos_banners="Loga &amp; bannery";
$l_splashscreens="Startovací okna";
$l_events="Události";

$l_development="Vývoj";
$l_join_us="Přidejte se!";
$l_current_work_todo_list="Probíhající práce, TODO list";
$l_latest_cvs_commits="Poslední aktualizace SVN";
$l_browse_code="Procházet kód";
$l_web_cvs="Web SVN";
$l_gui_translation="Překlad GUI";
$l_user_manual_translation="Překlad už. dokumentace";
$l_website_translation="Překlad WWW stránek";
$l_upload="Upload";

$l_links="Odkazy";
$l_user_progs="Uživatelské programy";
$l_sponsors="Sponzoři";
$l_donation="Dary";
$l_development_tools="Vývoj. nástroje";

$l_contacts="Kontakty";
$l_on_line_chat="On-line chat";
$l_forum="Fórum";
$l_mailinglist="Mailová konference";
$l_guestbook="Kniha návštěv";
$l_credits="Tým";

$l_misc="Různé";
$l_license="Licence";
$l_sitemap="Mapa webu";

// Stats module
$l_user_online = "Uživatelů online";
$l_visitors_since = "Návštěvníci od 22.09.98";

// Forum module
$l_forum_description="Diskuzní <a href=\"phorum5/\">fórum</a> pro KDevelop, <a href=\"http://www.kde.org/\">KDE</a> a <a href=\"http://www.trolltech.com\">Qt</a>.";

// IRC module
$l_irc_description="S ostatními uživateli a vývojáři se můžete setkat na IRC <a href=\"chat/\"><em>#kdevelop</em> kanálu na <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Galerie";
$l_picture_corner_description="KDevelop 3.0 v IDEAl módu v KDE 3.2 s tématem Plastik";

// User Programs module
$l_total = "celkem:";
$l_newest_entries = "<b>%s</b> nejnovějších";
$l_by = "od";

// Downloads Per Hour module
$l_downloads_per_hour = "Počet stažení za hodinu";

// ChangeLog module
$l_change_log = "Historie změn";

// Content module
$l_page_is_outdated = "<b>Tato stránka je neaktuální</b>, existuje novější <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">anglická verze</a>";
$l_translation_by = "Správce českého překladu: ";
$l_last_updated = "Tato stránka byla naposled aktualizována ";
$l_website_bugs = "Jestliže máte jakýkoli problém, týkající se stránek, kontaktujte ";

// "Other versions" links
$l_other_versions="Další verze";
$l_other_news="Další novinky";
$l_branches_compiling_section_at="Kompilační sekce pro";
$l_bugs_section_at="Sekce chyb &amp; přání";
$l_download_section_at="Download pro";
$l_requirements_section_at="Požadavky pro";
$l_tutorials_section_at="Návody a ukázky pro";

// Page titles
$l_pt_main="IDE - domovská stránka";
$l_pt_main_year="Novinky %d";
$l_pt_versions="Vydané verze";
$l_pt_in_the_press="V tisku";
$l_pt_license="Licence";
$l_pt_donate="Dary a sponzoring";
$l_pt_website_translation_status="Stav překladu stránek";
$l_pt_optional_files_translation_status="Stav překladu stránek (volitelné soubory)";
$l_pt_sitemap="Mapa webu (sitemap)";
$l_pt_upload="Upload";
$l_pt_current_work="Probíhající práce";
$l_pt_join_the_team="Přidejte se!";
$l_pt_awards="Ocenění";
$l_pt_logos_banners="Loga &amp; bannery";
$l_pt_pic_corner="Archiv galerie";
$l_pt_splashscreens="Startovací okna";
$l_pt_users="Programy od uživatelů";
$l_pt_sponsors="Sponzoři";
$l_pt_links_development="Vývojářské odkazy";
$l_pt_links_tools="Vývojářské nástroje";
$l_pt_mailinglist="Mailová konference";
$l_pt_bugs="Chyby &amp; přání";
$l_pt_stats="Statistiky webu";
$l_pt_doc_technotes_index="Index tech. poznámek";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Kniha návštěv - archiv";
$l_pt_guestbook_guestbook_010203_1999="Kniha návštěv Led/Úno/Bře 1999";
$l_pt_guestbook_guestbook_040506_1999="Kniha návštěv Dub/Kvě/Čen 1999";
$l_pt_guestbook_guestbook_0708_1999="Kniha návštěv Čec/Srp 1999";
$l_pt_guestbook_guestbook_091011_1999="Kniha návštěv Zář/Říj/Lis 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Kniha návštěv Pro/Led/Úno/Bře 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Kniha návštěv Dub 2000 / Čec 2004";
$l_pt_events="události";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x hlavní informace";
$l_pt_1_3_announce_kdevelop_1_3="ohlášení verze 1.3";
$l_pt_1_3_authors="1.x autoři";
$l_pt_1_3_changes="1.x změny";
$l_pt_1_3_features="1.x vlastnosti";
$l_pt_1_3_pressrelease1_0="1.0 tisková zpráva";
$l_pt_1_3_pressrelease1_1="1.1 tisková zpráva";
$l_pt_1_3_screenshots1="1.x snímky obrazovky, sekce 1";
$l_pt_1_3_screenshots2="1.x snímky obrazovky, sekce 2";
$l_pt_1_3_screenshots3="1.x snímky obrazovky, sekce 3";
$l_pt_2_1_kdevelop="2.x hlavní informace";
$l_pt_2_1_announce_kdevelop_2_0="ohlášení verze 2.0";
$l_pt_2_1_authors="2.x autoři";
$l_pt_2_1_changes="2.x změny";
$l_pt_2_1_faq="2.x FAQ";
$l_pt_2_1_features="2.x vlastnosti";
$l_pt_2_1_screenshots1="2.x snímky obrazovky, sekce 1";
$l_pt_2_1_screenshots2="2.x snímky obrazovky, sekce 2";
$l_pt_2_1_screenshots3="2.x snímky obrazovky, sekce 3";
$l_pt_x_x_kdevelop="%s.x hlavní informace";
$l_pt_x_x_announce_kdevelop="ohlášení verze %s";
$l_pt_x_x_authors="%s.x autoři";
$l_pt_x_x_branches_compiling="%s.x SVN vývojové větve &amp; kompilace";
$l_pt_x_x_changes="%s.x změny";
$l_pt_x_x_faq="%s.x FAQ";
$l_pt_x_x_download="%s.x download";
$l_pt_x_x_features="%s.x vlastnosti";
$l_pt_x_x_kdevelop_po_status="%s.x GUI - stav překladu";
$l_pt_x_x_requirements="%s.x požadavky";
$l_pt_x_x_screenshots="%s.x snímky obrazovky";
$l_pt_x_x_screenshots1="%s.x snímky obrazovky, sekce 1";
$l_pt_x_x_screenshots2="%s.x snímky obrazovky, sekce 2";
$l_pt_x_x_screenshots3="%s.x snímky obrazovky, sekce 3";
$l_pt_x_x_tutorials="%s.x návody, postupy";
$l_pt_x_x_doc_tutorial_autoconf="%s.x návod pro Autoconf/Automake"; 
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI tutorial";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia tutorial";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"Uživatelsky definované nastavení\" Tutorial";
$l_pt_x_x_ChangeLog="%s.x Individuální commity do SVN";
$l_pt_HEAD_kdevelop="HEAD hlavní informace";
$l_pt_HEAD_authors="HEAD autoři";
$l_pt_HEAD_branches_compiling="HEAD SVN vývojové větve &amp; kompilace";
$l_pt_HEAD_changes="HEAD změny";
$l_pt_HEAD_ChangeLog="Individuální commity do SVN větve HEAD";
$l_pt_HEAD_faq="HEAD FAQ";
$l_pt_HEAD_download="HEAD download";
$l_pt_HEAD_features="HEAD vlastnosti";
$l_pt_HEAD_kdevelop_po_status="HEAD GUI - stav překladu";
$l_pt_HEAD_requirements="HEAD požadavky";
$l_pt_HEAD_screenshots="HEAD snímky obrazovky";
$l_pt_HEAD_screenshots1="HEAD snímky obrazovky, sekce 1";
$l_pt_HEAD_screenshots2="HEAD snímky obrazovky, sekce 2";
$l_pt_HEAD_screenshots3="HEAD snímky obrazovky, sekce 3";
$l_pt_tutorials="návody, postupy";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
