<?php
// kate: encoding iso-8859-1
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'iso-8859-1';

// The php locale, LanguageCode_CountryCode
$l_locale= 'de_DE';

$l_graphic_mode = "Grafikmodus";
$l_text_mode = "Textmodus";

// Logo
$l_back_kdevelop_home="Zur&uuml;ck zur KDevelop-Hauptseite";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Englisch",
                   "ar" => "Arabisch",
                   "cs" => "Tschechisch",
                   "de" => "Deutsch",
                   "es" => "Spanisch",
                   "fr" => "Franz&ouml;sisch",
                   "hu" => "Ungarisch",
                   "id" => "Indonesisch",
                   "it" => "Italienisch",
                   "nl" => "Niederl&auml;ndisch",
                   "pt" => "Portugiesisch",
                   "pt_BR" => "Brasilianisches Portugiesisch",
                   "pl" => "Polnisch",
                   "ro" => "Rum&auml;nisch",
                   "ru" => "Russisch",
                   "tr" => "T&uuml;rkisch",
                   "uk" => "Ukrainianisch",
                   "zh_CN" => "Vereinfachtes Chinesisch");

$l_more_elipsis = 'mehr ...';

$l_what_is_KDevelop = 'Was ist KDevelop?';
$l_def_KDevelop = 'ist eine freie, quelloffene IDE (integrierte Entwicklungsumgebung) f&uuml;r MS&nbsp;Windows, Mac&nbsp;OS&nbsp;X, Linux, Solaris und FreeBSD. Es hat viele Funktionen, ist modular erweiterbar und kann f&uuml;r C/C++ sowie weitere Sprachen verwendet werden. KDevelop basiert auf KDevPlatform, die KDE- und Qt-Bibliotheken und wird seit 1998 entwickelt.';
$l_def_KDevPlatform = 'ist eine freie, quelloffene Zusammenstellung von Bibliotheken, die als Basis f&uuml;r die Entwicklung IDE-&auml;hnlicher Anwendungen verwendet werden k&ouml;nnen. Es ist nicht auf eine Programmiersprache beschr&auml;nkt und soll in Anwendungen wie KDevelop, Quanta, Kile, KTechLab usw. zum Einsatz kommen.';
$l_def_KDevelop4 = 'ist eine grundlegende Neuentwicklung auf Basis von Qt&nbsp;4/KDE&nbsp;4 mit leistungsf&auml;higer Sprachen-Architektur. Es befindet sich in der hei&szlig;en Entwicklungsphase (derzeit im Beta-Stadium) und unterst&uuml;tzt C++- und PHP-Entwicklung mit auf CMake oder eigenen Makefiles basierendem Build-System. Empfohlen f&uuml;r Linux (<b>k&ouml;nnte auf anderen Systemen ebenfalls laufen</b>, ist aber noch nicht getestet).';
$l_def_KDevelop3 = 'ist sehr stabil und ausgereift, basiert auf Qt&nbsp;3/KDE&nbsp;3 und unterst&uuml;tzt viele Programmiersprachen und Build-Systeme. Es wird nicht mehr weiter entwickelt; unterst&uuml;tzt wird nur Linux.';

// cvsbranches.ihtml page
$l_unstable_development = 'Unstable f&uuml;r %s';
$l_stable_version = 'Stable f&uuml;r %s';
$l_entirely_new_code = 'v&ouml;llig neue Code-Basis, von Grund auf neu geschrieben';
$l_was_released_with = 'wurde ver&ouml;ffentlicht mit';
$l_bugfix_versions = 'Versionen';
$l_scheduled_for_versions = 'geplant f&uuml;r Version';
$l_scheduled_versions = '%s Bugfix %s wird zusammen mit %s ver&ouml;ffentlicht';
$l_release_schedule = '%s-Release-Plan';

// Google module
$l_search="Suche";

// Quick download module
$l_quick_downloads = "Aktuelle Downloads";
$l_current_stable_version = "Aktuelle stabile Version";
$l_current_development_version = "Aktuelle Entwicklerversion";

// Menu module
$l_website_navigation="Navigation";
$l_all_versions="Alle&nbsp;Versionen";
$l_general="Allgemein";
$l_home="Startseite";
$l_versions="Versionen";
$l_features="Eigenschaften";
$l_requirements="Anforderungen";
$l_download="Download";
$l_cvs_branches_compiling="SVN-Zweige&nbsp;&amp; Kompilieren";
$l_changes="&Auml;nderungen";
$l_bugs_wishes="Fehler&nbsp;&amp; Anregungen";

$l_documentation="Dokumentation";
$l_user_manual="Benutzerhandbuch";
$l_api_documentation="Dokumentation der&nbsp;API";
$l_platform_api_documentation="Dokumentation der Plattform-API";
$l_tutorials="Anleitungen";
$l_faq="FAQ";
$l_technotes="Technische Hinweise";
$l_mediawiki="Wiki";

$l_presentations_graphics="Pr&auml;sentationen und Grafiken";
$l_screenshots="Bildschirmfotos";
$l_in_the_press="In der Presse";
$l_awards="Auszeichnungen";
$l_logos_banners="Logos&nbsp;&amp; Banner";
$l_splashscreens="Startbildschirme";
$l_events="Veranstaltungen";

$l_development="Entwicklung";
$l_join_us="Mach mit!";
$l_current_work_todo_list="Derzeitige Arbeit, TODO-Liste";
$l_latest_cvs_commits="Letzte SVN-Commits";
$l_browse_code="Durchforste den Code";
$l_web_cvs="Web-SVN";
$l_gui_translation="&Uuml;bersetzung der GUI";
$l_user_manual_translation="&Uuml;bersetzung des Handbuchs";
$l_website_translation="&Uuml;bersetzungen der Webseite";
$l_upload="Hochladen";

$l_links="Links";
$l_user_progs="Programme von Benutzern";
$l_sponsors="Sponsoren";
$l_donation="Spenden";
$l_development_tools="Entwicklungs- werkzeuge";

$l_contacts="Kontakt";
$l_on_line_chat="Online-Chat";
$l_forum="Forum";
$l_mailinglist="Mailingliste";
$l_guestbook="G&auml;stebuch";
$l_credits="Das Team";

$l_misc="Verschiedenes";
$l_license="Lizenz";
$l_sitemap="&Uuml;bersicht (Sitemap)";

// Stats module
$l_user_online = "Benutzer online";
$l_visitors_since = "Besucher seit dem 22.09.1998";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Diskussionsforum</a> f&uuml;r KDevelop-, <a href=\"http://www.kde.org/\">KDE</a>- und <a href=\"http://www.trolltech.com\">Qt</a>-verwandte Dinge.";

// IRC module
$l_irc_description="Sie k&ouml;nnen andere Benutzer und Entwickler im Kanal <a href=\"chat/\"><em>#kdevelop</em> auf <em>irc.kde.org</em></a> treffen.";

// Picture Corner module
$l_picture_corner="Bilderecke";
$l_picture_corner_description="KDevelop 3.0 im IDEAl-Modus mit dem KDE 3.2 Plastik-Theme";

// User Programs module
$l_total = "gesamt:";
$l_newest_entries = "die neusten <b>%s</b> Eintr&auml;ge";
$l_by = "von";

// Downloads Per Hour module
$l_downloads_per_hour = "Downloads pro Stunde";

// ChangeLog module
$l_change_log = "&Auml;nderungen";

// Content module
$l_page_is_outdated = "<b>Diese Seite ist nicht mehr aktuell</b>, eine neuere <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">englische Version</a> existiert.";
$l_translation_by = "Deutsche &Uuml;bersetzung bereitgestellt von ";
$l_last_updated = "Diese Seite wurde zuletzt aktualisiert am ";
$l_website_bugs = "Sollte ein Problem auf der Seite auftreten, kontaktieren Sie den ";
$l_latest_blog_posts = "Neuigkeiten auf Blogs der KDevelop-Entwickler";

// "Other versions" links
$l_other_versions="Weitere Versionen";
$l_other_news="Weitere Nachrichten";
$l_branches_compiling_section_at="Bereich Kompilieren der";
$l_bugs_section_at="Bereich Fehler &amp; Anregungen der";
$l_download_section_at="Bereich Download der";
$l_requirements_section_at="Bereich Anforderungen der";
$l_tutorials_section_at="Bereich Anleitungen der";

// Page titles
$l_pt_main="Integrierte Entwicklungsumgebung - Homepage";
$l_pt_main_year="Neues %d";
$l_pt_versions="Freigegebene Versionen";
$l_pt_in_the_press="In der Presse";
$l_pt_license="Lizenz";
$l_pt_donate="Spenden und Sponsoring";
$l_pt_website_translation_status="&Uuml;bersetzungsstatus der Webseite";
$l_pt_optional_files_translation_status="&Uuml;bersetzungsstatus der Webseite (optionale Dateien)";
$l_pt_sitemap="&Uuml;bersicht (Sitemap)";
$l_pt_upload="Hochladen";
$l_pt_current_work="Derzeitige Arbeit";
$l_pt_join_the_team="Mach mit!";
$l_pt_awards="Auszeichnungen";
$l_pt_logos_banners="Logos &amp; Banner";
$l_pt_pic_corner="Bildereckenarchiv";
$l_pt_splashscreens="Startbildschirme";
$l_pt_users="Programme von Benutzern";
$l_pt_sponsors="Sponsoren";
$l_pt_links_development="Enwickler-Links";
$l_pt_links_tools="Entwicklungswerkzeuge";
$l_pt_mailinglist="Mailinglisten";
$l_pt_bugs="Fehler &amp; Anregungen";
$l_pt_stats="Webseitenstatistik";
$l_pt_doc_technotes_index="Technische Hinweise - Index";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="G&auml;stebucharchiv";
$l_pt_guestbook_guestbook_010203_1999="G&auml;stebuch Jan/Feb/M&auml;r 1999";
$l_pt_guestbook_guestbook_040506_1999="G&auml;stebuch Apr/Mai/Jun 1999";
$l_pt_guestbook_guestbook_0708_1999="G&auml;stebuch Jul/Aug 1999";
$l_pt_guestbook_guestbook_091011_1999="G&auml;stebuch Sep/Okt/Nov 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="G&auml;stebuch Dez/Jan/Feb/M&auml;r 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="G&auml;stebuch Apr 2000 - Jul 2004";
$l_pt_events="Veranstaltungen";
$l_pt_events_linuxtag2000="LinuxTag 2000";
$l_pt_events_linuxtag2001="LinuxTag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x Hauptinfoseite";
$l_pt_1_3_announce_kdevelop_1_3="1.3 Freigabemitteilung";
$l_pt_1_3_authors="1.x Autoren";
$l_pt_1_3_changes="1.x &Auml;nderungen";
$l_pt_1_3_features="1.x Eigenschaften";
$l_pt_1_3_pressrelease1_0="1.0 Pressemittelung";
$l_pt_1_3_pressrelease1_1="1.1 Pressemittelung";
$l_pt_1_3_screenshots1="1.x Bildschirmfotos Seite 1";
$l_pt_1_3_screenshots2="1.x Bildschirmfotos Seite 2";
$l_pt_1_3_screenshots3="1.x Bildschirmfotos Seite 3";
$l_pt_2_1_kdevelop="2.x Hauptinfoseite";
$l_pt_2_1_announce_kdevelop_2_0="2.0 Freigabemitteilung";
$l_pt_2_1_authors="2.x Autoren";
$l_pt_2_1_changes="2.x &Auml;nderungen";
$l_pt_2_1_faq="2.x FAQ";
$l_pt_2_1_features="2.x Eigenschaften";
$l_pt_2_1_screenshots1="2.x Bildschirmfotos Seite 1";
$l_pt_2_1_screenshots2="2.x Bildschirmfotos Seite 2";
$l_pt_2_1_screenshots3="2.x Bildschirmfotos Seite 3";
$l_pt_x_x_kdevelop="%s.x Hauptinfoseite";
$l_pt_x_x_announce_kdevelop="%s Freigabemitteilung";
$l_pt_x_x_authors="%s.x Autoren";
$l_pt_x_x_branches_compiling="%s.x SVN-Zweige &amp; Kompilieren";
$l_pt_x_x_changes="%s.x &Auml;nderungen";
$l_pt_x_x_faq="%s.x FAQ";
$l_pt_x_x_download="%s.x Download";
$l_pt_x_x_features="%s.x Eigenschaften";
$l_pt_x_x_kdevelop_po_status="%s.x GUI-&Uuml;bersetzungsstatus";
$l_pt_x_x_requirements="%s.x Anforderungen";
$l_pt_x_x_screenshots="%s.x Bildschirmfotos";
$l_pt_x_x_screenshots1="%s.x Bildschirmfotos Seite 1";
$l_pt_x_x_screenshots2="%s.x Bildschirmfotos Seite 2";
$l_pt_x_x_screenshots3="%s.x Bildschirmfotos Seite 3";
$l_pt_x_x_tutorials="%s.x Anleitungen";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Anleitungen f&uuml;r Autoconf/Automake";
$l_pt_x_x_doc_kmditutorial_index="%s.x Anleitung f&uuml;r KMDI";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Anleitung f&uuml;r Qtopia";
$l_pt_x_x_doc_tutorial_settings_index="%s.x Anleitung f&uuml;r \"Benutzerdefinierte Einstellungen\"";
$l_pt_x_x_ChangeLog="%s. SVN-Commits";
$l_pt_HEAD_kdevelop="HEAD Hauptinfoseite";
$l_pt_HEAD_authors="HEAD Autoren";
$l_pt_HEAD_branches_compiling="HEAD SVN-Zweige &amp; Kompilieren";
$l_pt_HEAD_changes="HEAD &Auml;nderungen";
$l_pt_HEAD_ChangeLog="HEAD SVN-Commits";
$l_pt_HEAD_faq="HEAD FAQ";
$l_pt_HEAD_download="HEAD Download";
$l_pt_HEAD_features="HEAD Eigenschaften";
$l_pt_HEAD_kdevelop_po_status="HEAD GUI-&Uuml;bersetzungsstatus";
$l_pt_HEAD_requirements="HEAD Anforderungen";
$l_pt_HEAD_screenshots="HEAD Bildschirmfotos";
$l_pt_HEAD_screenshots1="HEAD Bildschirmfotos Seite 1";
$l_pt_HEAD_screenshots2="HEAD Bildschirmfotos Seite 2";
$l_pt_HEAD_screenshots3="HEAD Bildschirmfotos Seite 3";
$l_pt_tutorials="Anleitungen";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
