<?php
// kate: encoding iso-8859-1
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'iso-8859-1';

// The php locale, LanguageCode_CountryCode
$l_locale= 'nl_NL';

$l_graphic_mode = "Grafische Modus";
$l_text_mode = "Tekst Modus";

// Logo
$l_back_kdevelop_home="terug naar KDevelop home";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Engels",
                   "ar" => "Arabisch",
                   "cs" => "Tjechisch",
                   "de" => "Duits",
                   "es" => "Spaans",
                   "fr" => "Frans",
                   "hu" => "Hongaars",
                   "id" => "Indonesisch",
                   "it" => "Italiaans",
                   "nl" => "Nederlands",
                   "pt" => "Portugees",
                   "pt_BR" => "Braziliaans Portugees",
                   "pl" => "Pools",
                   "ro" => "Roemeens",
                   "ru" => "Russisch",
                   "tr" => "Turks",
                   "uk" => "Oekra&iuml;ens",
                   "zh_CN" => "Vereenvoudigd Chinees");

// Google module
$l_search="Zoeken";

// Quick download module
$l_quick_downloads = "Snel downloaden";
$l_current_stable_version = "Huidige stabiele versie";
$l_current_development_version = "Huidige ontwikkelingsversie";

// Menu module
$l_website_navigation="Website navigatie";
$l_all_versions="alle&nbsp;versies";
$l_general="Algemeen";
$l_home="Home";
$l_versions="Versies";
$l_features="Features";
$l_requirements="Benodigdheden";
$l_download="Downloaden";
$l_cvs_branches_compiling="SVN Branches &amp; Compileren";
$l_changes="Veranderingen";
$l_bugs_wishes="Bugs &amp; wensen";

$l_documentation="Documentatie";
$l_user_manual="Gebruikers handleiding";
$l_api_documentation="API documentatie";
$l_platform_api_documentation="Platform API";
$l_tutorials="Tutorials";
$l_faq="F.A.Q.";
$l_technotes="TechNotes";
$l_mediawiki="Wiki";

$l_presentations_graphics="Presentaties en Afbeeldingen";
$l_screenshots="Screenshots";
$l_in_the_press="In de pers";
$l_awards="Gewonnen prijzen";
$l_logos_banners="Logo&#039;s &amp; Banners";
$l_splashscreens="Splashscreens";
$l_events="Gebeurtenissen";

$l_development="Ontwikkelingen";
$l_join_us="Help mee!";
$l_current_work_todo_list="Huidig werk, TODO lijst";
$l_latest_cvs_commits="Laatste SVN toevoegingen";
$l_browse_code="Blader door de code";
$l_web_cvs="Web SVN";
$l_gui_translation="GUI vertalingen";
$l_user_manual_translation="Gebruikers&#173;handleiding vertalingen";
$l_website_translation="Website vertalingen";
$l_upload="Upload";

$l_links="Links";
$l_user_progs="Gebruiker programma&#039;s";
$l_sponsors="Sponsors";
$l_donation="Donaties";
$l_development_tools="Ontwikkelings tools";

$l_contacts="Contacten";
$l_on_line_chat="On-line chat";
$l_forum="Forum";
$l_mailinglist="Mailinglist";
$l_guestbook="Gastenboek";
$l_credits="Het team";

$l_misc="Overig";
$l_license="Licentie";
$l_sitemap="Sitemap";

// Stats module
$l_user_online = "Gebruikers online";
$l_visitors_since = "Bezoekers sinds 09/22/98";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Discussie forum</a> over KDevelop, <a href=\"http://www.kde.org/\">KDE</a> en aan <a href=\"http://www.trolltech.com\">Qt</a> gerelateerde onderwerpen.";

// IRC module
$l_irc_description="Andere gebruikers en ontwikkelaars kun je ontmoeten in het <a href=\"chat/\"><em>#kdevelop</em> channel op <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Plaatjeshoek";
$l_picture_corner_description="KDevelop 3.0 in IDEAl modus in KDE 3.2 met het Plastik thema";

// User Programs module
$l_total = "totaal:";
$l_newest_entries = "nieuwste <b>%s</b> toevoegingen";
$l_by = "door";

// Downloads Per Hour module
$l_downloads_per_hour = "Downloads per uur";

// ChangeLog module
$l_change_log = "ChangeLog";

// Content module
$l_page_is_outdated = "<b>Deze pagina is verouderd</b>, een nieuwere <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">engelse versie</a> is beschikbaar";
$l_translation_by = "Nederlandse vertaling onderhouden door ";
$l_last_updated = "Deze pagina is het laatst bijgewerkt op: ";
$l_website_bugs = "Als er problemen zijn met de website, neem contact op met de ";

// "Other versions" links
$l_other_versions="Andere versies";
$l_other_news="Ander nieuws";
$l_branches_compiling_section_at="Compileersectie op";
$l_bugs_section_at="Bugs &amp; wensen sectie op";
$l_download_section_at="Download sectie op";
$l_requirements_section_at="Benodigdheden sectie op";
$l_tutorials_section_at="Tutorials sectie op";

// Page titles
$l_pt_main="een geintegreerde ontwikkelingsomgeving - Homepage";
$l_pt_main_year="Nieuws van %d";
$l_pt_versions="Uitgebrachte versies";
$l_pt_in_the_press="In de Pers";
$l_pt_license="Licentie";
$l_pt_donate="Donaties en Sponsoren";
$l_pt_website_translation_status="Website vertaling status";
$l_pt_optional_files_translation_status="Website vertaling status (optionele bestanden)";
$l_pt_sitemap="Website kaart (sitemap)";
$l_pt_upload="Upload";
$l_pt_current_work="Huidig werk";
$l_pt_join_the_team="Help mee!";
$l_pt_awards="Gewonnen prijzen";
$l_pt_logos_banners="Logo's &amp; Banners";
$l_pt_pic_corner="Plaatjeshoek archief";
$l_pt_splashscreens="Splashscreens";
$l_pt_users="Gebruikersprogramma's";
$l_pt_sponsors="Sponsors";
$l_pt_links_development="Ontwikkeling Links";
$l_pt_links_tools="Ontwikkeling Tools";
$l_pt_mailinglist="Mailinglist";
$l_pt_bugs="Bugs &amp; Wensen";
$l_pt_stats="Website statistieken";
$l_pt_doc_technotes_index="TechNotes Index";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Gastenboek archieven";
$l_pt_guestbook_guestbook_010203_1999="Gastenboek Jan/Feb/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Gastenboek Apr/May/Jun 1999";
$l_pt_guestbook_guestbook_0708_1999="Gastenboek Jul/Aug 1999";
$l_pt_guestbook_guestbook_091011_1999="Gastenboek Sep/Oct/Nov 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Gastenboek Dec/Jan/Feb/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Gastenboek Apr 2000 / Jul 2004";
$l_pt_events="Gebeurtenissen";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x main info";
$l_pt_1_3_announce_kdevelop_1_3="1.3 release aankondiging";
$l_pt_1_3_authors="1.x auteurs";
$l_pt_1_3_changes="1.x veranderingen";
$l_pt_1_3_features="1.x features";
$l_pt_1_3_pressrelease1_0="1.0 persbericht";
$l_pt_1_3_pressrelease1_1="1.1 persbericht";
$l_pt_1_3_screenshots1="1.x screenshots sectie 1";
$l_pt_1_3_screenshots2="1.x screenshots sectie 2";
$l_pt_1_3_screenshots3="1.x screenshots sectie 3";
$l_pt_2_1_kdevelop="2.x main info";
$l_pt_2_1_announce_kdevelop_2_0="2.0 release aankondiging";
$l_pt_2_1_authors="2.x auteurs";
$l_pt_2_1_changes="2.x veranderingen";
$l_pt_2_1_faq="2.x FAQ";
$l_pt_2_1_features="2.x features";
$l_pt_2_1_screenshots1="2.x screenshots sectie 1";
$l_pt_2_1_screenshots2="2.x screenshots sectie 2";
$l_pt_2_1_screenshots3="2.x screenshots sectie 3";
$l_pt_x_x_kdevelop="%s.x main info";
$l_pt_x_x_announce_kdevelop="%s release aankondiging";
$l_pt_x_x_authors="%s.x auteurs";
$l_pt_x_x_branches_compiling="%s.x SVN Branches &amp; Compileren";
$l_pt_x_x_changes="%s.x veranderingen";
$l_pt_x_x_faq="%s.x FAQ";
$l_pt_x_x_download="%s.x download";
$l_pt_x_x_features="%s.x features";
$l_pt_x_x_kdevelop_po_status="%s.x GUI vertalingstatus";
$l_pt_x_x_requirements="%s.x benodigdheden";
$l_pt_x_x_screenshots="%s.x screenshots";
$l_pt_x_x_screenshots1="%s.x screenshots sectie 1";
$l_pt_x_x_screenshots2="%s.x screenshots sectie 2";
$l_pt_x_x_screenshots3="%s.x screenshots sectie 3";
$l_pt_x_x_tutorials="%s.x tutorials";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Tutorial voor Autoconf/Automake"; 
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI tutorial";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia tutorial";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"Gebruikersinstellingen\" Tutorial";
$l_pt_x_x_ChangeLog="%s.x induviduele SVN commit logs";
$l_pt_HEAD_kdevelop="HEAD main info";
$l_pt_HEAD_authors="HEAD auteurs";
$l_pt_HEAD_branches_compiling="HEAD SVN Branches &amp; Compileren";
$l_pt_HEAD_changes="HEAD veranderingen";
$l_pt_HEAD_ChangeLog="HEAD induviduele SVN commit logs";
$l_pt_HEAD_faq="HEAD FAQ";
$l_pt_HEAD_download="HEAD download";
$l_pt_HEAD_features="HEAD features";
$l_pt_HEAD_kdevelop_po_status="HEAD GUI vertalingstatus";
$l_pt_HEAD_requirements="HEAD benodigdheden";
$l_pt_HEAD_screenshots="HEAD screenshots";
$l_pt_HEAD_screenshots1="HEAD screenshots sectie 1";
$l_pt_HEAD_screenshots2="HEAD screenshots sectie 2";
$l_pt_HEAD_screenshots3="HEAD screenshots sectie 3";
$l_pt_tutorials="tutorials";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
