<?php
// kate: encoding iso-8859-1
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'iso-8859-1';

// The php locale, LanguageCode_CountryCode
$l_locale= 'id_ID';

$l_graphic_mode = "Mode Grafis";
$l_text_mode = "Mode Teks";

// Logo
$l_back_kdevelop_home="kembali ke halaman utama KDevelop";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Inggris",
                   "ar" => "Arabic",
                   "cs" => "Ceko",
                   "de" => "Jerman",
                   "es" => "Spanyol",
                   "fr" => "Perancis",
                   "hu" => "Hungarian",
                   "id" => "Indonesia",
                   "it" => "Itali",
                   "nl" => "Belanda",
                   "pt" => "Portugis",
                   "pt_BR" => "Brazil-Portugis",
                   "pl" => "Polandia",
                   "ro" => "Romania",
                   "ru" => "Rusia",
                   "tr" => "Turki",
                   "uk" => "Ukraina",
                   "zh_CN" => "Cina yang disederhanakan");

// Google module
$l_search="Cari";

// Quick download module
$l_quick_downloads = "Download cepat";
$l_current_stable_version = "Versi stabil sekarang";
$l_current_development_version = "Versi yang dikembangkan sekarang";

// Menu module
$l_website_navigation="Navigasi website";
$l_all_versions="semua&nbsp;versi";
$l_general="Umum";
$l_home="Home";
$l_versions="Versi";
$l_features="Fitur";
$l_requirements="Requirement";
$l_download="Download";
$l_cvs_branches_compiling="Cabang SVN &amp; kompilasi";
$l_changes="Perubahan";
$l_bugs_wishes="Bug &amp; permintaan";

$l_documentation="Dokumentasi";
$l_user_manual="Petunjuk penggunaan";
$l_api_documentation="Dokumentasi API";
$l_platform_api_documentation="Platform API";
$l_tutorials="Panduan";
$l_faq="F.A.Q.(Pertanyaan yang sering ditanyakan)";
$l_technotes="Catatan teknis";
$l_mediawiki="Wiki";

$l_presentations_graphics="Presentasi dan Grafik";
$l_screenshots="Tampilan kilat";
$l_in_the_press="Di media cetak";
$l_awards="Penghargaan";
$l_logos_banners="Logo &amp; Iklan";
$l_splashscreens="Tampilan kilat";
$l_events="Acara/peristiwa";

$l_development="Pengembangan";
$l_join_us="Mari bergabung!";
$l_current_work_todo_list="Yang sedang dikerjakan,daftar TODO (yang harus dilakukan)";
$l_latest_cvs_commits="Kiriman SVN terbaru";
$l_browse_code="Lihat kode";
$l_web_cvs="SVN Web";
$l_gui_translation="Terjemahan GUI";
$l_user_manual_translation="Terjemahan buku panduan";
$l_website_translation="Terjemahan website";
$l_upload="Upload";

$l_links="Link";
$l_user_progs="Pengguna Program";
$l_sponsors="Sponsor";
$l_donation="Donasi";
$l_development_tools="Alat Pengembangan";

$l_contacts="Kontak";
$l_on_line_chat="Ngobrol on-line";
$l_forum="Forum";
$l_mailinglist="Milis";
$l_guestbook="Buku tamu";
$l_credits="Kredit";

$l_misc="Lain-lain";
$l_license="Lisensi";
$l_sitemap="Map situs";

// Stats module
$l_user_online = "Anggota online";
$l_visitors_since = "Jumlah Total Pengunjung sejak 09/22/98";

// Forum module
$l_forum_description="Diskusi <a href=\"phorum5/\">board</a> for KDevelop, <a href=\"http://www.kde.org/\">KDE</a> dan <a href=\"http://www.trolltech.com\">Qt</a> hal2 yang berhubungan.";

// IRC module
$l_irc_description="Anda dapat berinteraksi dengan user lainnya dan para developer lainnya di <a href=\"chat/\"><em>#kdevelop</em> channel di <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Arsip Gambar";
$l_picture_corner_description="KDevelop 3.0 baik digunakan di KDE 3.2 dengan tema Plastik";

// User Programs module
$l_total = "total:";
$l_newest_entries = "daftar <b>%s</b> terbaru";
$l_by = "dari";

// Downloads Per Hour module
$l_downloads_per_hour = "Download per jam";

// ChangeLog module
$l_change_log = "PerubahanLog";

// Content module
$l_page_is_outdated = "<b>Halaman ini sudah ketinggalan jaman</b>, terdapat halaman yang lebih baru <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">dalam bahasa Inggris</a>";
$l_translation_by = "Bahasa Indonesia diterjemahkan oleh ";
$l_last_updated = "Halaman ini terakhir diperbaharui pada tanggal : ";
$l_website_bugs = "Jika ada pertanyaan If there are any problems with the website, please contact the ";

// "Other versions" links
$l_other_versions="Versi yang lain";
$l_other_news="Berita baru yang lain";
$l_branches_compiling_section_at="Bagian kompilasi di";
$l_bugs_section_at="Bugs &amp; bagian permintaan di";
$l_download_section_at="Bagian download di";
$l_requirements_section_at="Bagian requirement di";
$l_tutorials_section_at="Bagian panduan di";

// Page titles
$l_pt_main="Pengembangan Integrasian Environment - Homepage";
$l_pt_main_year="Berita tahun %d";
$l_pt_versions="Versi yang telah dikeluarkan";
$l_pt_in_the_press="Di Media";
$l_pt_license="Lisensi";
$l_pt_donate="Donasi dan Sponsor";
$l_pt_website_translation_status="Status penerjemahan website";
$l_pt_optional_files_translation_status="Status penerjemahan website (file tambahan)";
$l_pt_sitemap="Map situs";
$l_pt_upload="Upload";
$l_pt_current_work="Yang sedang dikerjakan";
$l_pt_join_the_team="Gabung bersama kami!";
$l_pt_awards="Penghargaan";
$l_pt_logos_banners="Logo &amp; Iklan";
$l_pt_pic_corner="Arsip Gambar";
$l_pt_splashscreens="Tampilan kilat";
$l_pt_users="Program User";
$l_pt_sponsors="Sponsor";
$l_pt_links_development="Link Pengembangan";
$l_pt_links_tools="Alat-alat Pengembangan";
$l_pt_mailinglist="Mailinglist";
$l_pt_bugs="Bug &amp; Permintaan";
$l_pt_stats="Statistik website";
$l_pt_doc_technotes_index="Indeks Catatan Teknis";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Arsip Buku Tamu";
$l_pt_guestbook_guestbook_010203_1999="Buku Tamu Jan/Feb/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Buku Tamu Apr/May/Jun 1999";
$l_pt_guestbook_guestbook_0708_1999="Buku Tamu Jul/Aug 1999";
$l_pt_guestbook_guestbook_091011_1999="Buku Tamu Sep/Oct/Nov 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Buku Tamu Dec/Jan/Feb/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Buku Tamu Apr 2000 / Jul 2004";
$l_pt_events="acara/kejadian";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x main info";
$l_pt_1_3_announce_kdevelop_1_3="pengumuman rilis 1.3";
$l_pt_1_3_authors="1.x author";
$l_pt_1_3_changes="1.x perubahan";
$l_pt_1_3_features="1.x fitur";
$l_pt_1_3_pressrelease1_0="1.0 rilis media";
$l_pt_1_3_pressrelease1_1="1.1 rilis media";
$l_pt_1_3_screenshots1="1.x tampilan kilat bagian 1";
$l_pt_1_3_screenshots2="1.x tampilan kilat bagian 2";
$l_pt_1_3_screenshots3="1.x tampilan kilat bagian 3";
$l_pt_2_1_kdevelop="2.x info utama";
$l_pt_2_1_announce_kdevelop_2_0="2.0 pengumuman rilis";
$l_pt_2_1_authors="2.x author";
$l_pt_2_1_changes="2.x perubahan";
$l_pt_2_1_faq="2.x FAQ";
$l_pt_2_1_features="2.x fitur";
$l_pt_2_1_screenshots1="2.x tampilan kilat bagian 1";
$l_pt_2_1_screenshots2="2.x tampilan kilat bagian 2";
$l_pt_2_1_screenshots3="2.x tampilan kilat bagian 3";
$l_pt_x_x_kdevelop="%s.x info utama";
$l_pt_x_x_announce_kdevelop="%s pengumuman rilis";
$l_pt_x_x_authors="%s.x author";
$l_pt_x_x_branches_compiling="%s.x Cabang SVN &amp; Kompilasi";
$l_pt_x_x_changes="%s.x perubahan";
$l_pt_x_x_faq="%s.x FAQ";
$l_pt_x_x_download="%s.x download";
$l_pt_x_x_features="%s.x fitur";
$l_pt_x_x_kdevelop_po_status="%s.x status penerjemahan GUI";
$l_pt_x_x_requirements="%s.x requirement";
$l_pt_x_x_screenshots="%s.x tampilan kilat";
$l_pt_x_x_screenshots1="%s.x tampilan kilat bagian 1";
$l_pt_x_x_screenshots2="%s.x tampilan kilat bagian 2";
$l_pt_x_x_screenshots3="%s.x tampilan kilat bagian 3";
$l_pt_x_x_tutorials="%s.x panduan";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Panduan untuk Autoconf/Automake"; 
$l_pt_x_x_doc_kmditutorial_index="%s.x Panduan KMDI";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia tutorial";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"Definisi setting dari User\" Panduan";
$l_pt_x_x_ChangeLog="%s.x kiriman SVN terbaru";
$l_pt_HEAD_kdevelop="HEAD info menu";
$l_pt_HEAD_authors="HEAD author ";
$l_pt_HEAD_branches_compiling="KETUA Cabang SVN &amp; Kompilasi";
$l_pt_HEAD_changes="perubahan UTAMA";
$l_pt_HEAD_ChangeLog="HEAD kiriman SVN terbaru";
$l_pt_HEAD_faq="HEAD FAQ";
$l_pt_HEAD_download="HEAD download";
$l_pt_HEAD_features="HEAD fitur";
$l_pt_HEAD_kdevelop_po_status="HEAD status penerjemahan GUI";
$l_pt_HEAD_requirements="HEAD kebutuhan";
$l_pt_HEAD_screenshots="HEAD tampilan kilat";
$l_pt_HEAD_screenshots1="HEAD tampilan kilat bagian 1";
$l_pt_HEAD_screenshots2="HEAD tampilan kilat bagian 2";
$l_pt_HEAD_screenshots3="HEAD tampilan kilat bagian 3";
$l_pt_tutorials="panduan";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
