<?php
// kate: encoding iso-8859-1
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'iso-8859-1';

// The php locale, LanguageCode_CountryCode
$l_locale= 'it_IT';

$l_graphic_mode = "Modalit&agrave; Grafica";
$l_text_mode = "Modalit&agrave; Testuale";

// Logo
$l_back_kdevelop_home="torna a KDevelop home";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Inglese",
                   "ar" => "Arabic",
                   "cs" => "Ceco",
                   "de" => "Tedesco",
                   "es" => "Spagnolo",
                   "fr" => "Francese",
                   "hu" => "Hungarian",
                   "id" => "Indonesiano",
                   "it" => "Italiano",
                   "nl" => "Olandese",
                   "pt" => "Portoghese",
                   "pt_BR" => "Portoghese Brasiliano",
                   "pl" => "Polacco",
                   "ro" => "Rumeno",
                   "ru" => "Russo",
                   "tr" => "Turco",
                   "uk" => "Ucraino",
                   "zh_CN" => "Cinese Semplificato");

// Google module
$l_search="Cerca";

// Quick download module
$l_quick_downloads = "Download Rapidi";
$l_current_stable_version = "Versione stabile";
$l_current_development_version = "Versione in Sviluppo";

// Menu module
$l_website_navigation="Navigazione web";
$l_all_versions="tutte le versioni";
$l_general="Generale";
$l_home="Home";
$l_versions="Versioni";
$l_features="Caratteristiche";
$l_requirements="Requisiti";
$l_download="Download";
$l_cvs_branches_compiling="Rami SVN &amp; Compilazione";
$l_changes="Modifiche";
$l_bugs_wishes="Bugs &amp; desiderata";

$l_documentation="Documentazione";
$l_user_manual="Manuale Utente";
$l_api_documentation="Documentazione API";
$l_platform_api_documentation="Piattaforma API";
$l_tutorials="Tutoriale";
$l_faq="F.A.Q.";
$l_technotes="Note Tecniche";
$l_mediawiki="Wiki";

$l_presentations_graphics="Presentazioni e Grafica";
$l_screenshots="Schermate";
$l_in_the_press="Rassegna stampa";
$l_awards="Premi";
$l_logos_banners="Loghi &amp; Banner";
$l_splashscreens="Splashscreens";
$l_events="Eventi";

$l_development="Sviluppo";
$l_join_us="Unisciti a noi!";
$l_current_work_todo_list="Lavoro attuale, lista TODO";
$l_latest_cvs_commits="Ultimi commit SVN";
$l_browse_code="Naviga il codice";
$l_web_cvs="Web SVN";
$l_gui_translation="Traduzione GUI";
$l_user_manual_translation="Traduzione Manuale Utente";
$l_website_translation="Traduzione Sito Web";
$l_upload="Upload";

$l_links="Links";
$l_user_progs="Programmi degli utenti";
$l_sponsors="Sponsors";
$l_donation="Donazioni";
$l_development_tools="Strumenti di sviluppo";

$l_contacts="Contatti";
$l_on_line_chat="Chat on-line";
$l_forum="Forum";
$l_mailinglist="Mailinglist";
$l_guestbook="Guestbook";
$l_credits="Ringraziamenti";

$l_misc="Varie";
$l_license="Licenza";
$l_sitemap="Mappa del sito";

// Stats module
$l_user_online = "Utenti online";
$l_visitors_since = "Visitatori dal 22/09/98";

// Forum module
$l_forum_description="Discussioni <a href=\"phorum5/\">board</a> su KDevelop, <a href=\"http://www.kde.org/\">KDE</a> e argomenti legati a <a href=\"http://www.trolltech.com\">Qt</a>.";

// IRC module
$l_irc_description="Puoi incontrare altri utenti e sviluppatori sul canale <a href=\"chat/\"><em>#kdevelop</em> su
<em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Angolo delle immagini";
$l_picture_corner_description="KDevelop 3.0 in IDEAl mode su KDE 3.2 con il tema Plastik";

// User Programs module
$l_total = "totale:";
$l_newest_entries = "ultimi <b>%s</b> arrivi";
$l_by = "da";

// Downloads Per Hour module
$l_downloads_per_hour = "Download per ora";

// ChangeLog module
$l_change_log = "Lista delle modifiche";

// Content module
$l_page_is_outdated = "<b>Questa pagina &egrave; vecchia</b>, ne esiste una <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">versione nuova in inglese</a>";
$l_translation_by = "Traduzione italiana mantenuta da ";
$l_last_updated = "Questa pagina &egrave; stata aggiornata il: ";
$l_website_bugs = "Se ci sono problemi con il sito web, prego contattare il ";

// "Other versions" links
$l_other_versions="Altre versioni";
$l_other_news="Altre notizie";
$l_branches_compiling_section_at="Sezione Compilazione int";
$l_bugs_section_at="Sezione Bugs &amp; desideri in";
$l_download_section_at="Sezione Download in";
$l_requirements_section_at="Sezione Requisiti in";
$l_tutorials_section_at="Sezione Tutorials in";

// Page titles
$l_pt_main="un Ambiente di Sviluppo Integrato - Homepage";
$l_pt_main_year="Notizie del %d";
$l_pt_versions="Versioni rilasciate";
$l_pt_in_the_press="Rassegna Stampa";
$l_pt_license="Licenza";
$l_pt_donate="Donazioni e Sponsor";
$l_pt_website_translation_status="Stato traduzione sito Web";
$l_pt_optional_files_translation_status="Stato traduzione sito Web (files opzionali)";
$l_pt_sitemap="Mappa Sito Web";
$l_pt_upload="Upload";
$l_pt_current_work="Lavoro attuale";
$l_pt_join_the_team="Unisciti a noi!";
$l_pt_awards="Premi";
$l_pt_logos_banners="Loghi &amp; Banners";
$l_pt_pic_corner="Archivio dell'angolo delle immagini";
$l_pt_splashscreens="Splashscreens";
$l_pt_users="Programmi degli utenti";
$l_pt_sponsors="Sponsors";
$l_pt_links_development="Links sviluppo";
$l_pt_links_tools="Strumenti di Sviluppo";
$l_pt_mailinglist="Mailinglist";
$l_pt_bugs="Bugs &amp; Desideri";
$l_pt_stats="Statistiche sito Web";
$l_pt_doc_technotes_index="Indici TechNotes";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Archivi Guestbook";
$l_pt_guestbook_guestbook_010203_1999="Guestbook Gen/Feb/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Guestbook Apr/Mag/Giu 1999";
$l_pt_guestbook_guestbook_0708_1999="Guestbook Lug/Ago 1999";
$l_pt_guestbook_guestbook_091011_1999="Guestbook Set/Ott/Nov 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Guestbook Dic/Gen/Feb/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Guestbook Apr 2000 / Jul 2004";
$l_pt_events="eventi";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x info principali";
$l_pt_1_3_announce_kdevelop_1_3="1.3 annuncio rilascio";
$l_pt_1_3_authors="1.x autori";
$l_pt_1_3_changes="1.x modifiche";
$l_pt_1_3_features="1.x caratteristiche";
$l_pt_1_3_pressrelease1_0="1.0 rassegna stampa";
$l_pt_1_3_pressrelease1_1="1.1 rassegna stampa";
$l_pt_1_3_screenshots1="1.x schermate sezione 1";
$l_pt_1_3_screenshots2="1.x schermate sezione 2";
$l_pt_1_3_screenshots3="1.x schermate sezione 3";
$l_pt_2_1_kdevelop="2.x info principali";
$l_pt_2_1_announce_kdevelop_2_0="2.0 annuncio rilascio";
$l_pt_2_1_authors="2.x autori";
$l_pt_2_1_changes="2.x modifiche";
$l_pt_2_1_faq="2.x FAQ";
$l_pt_2_1_features="2.x caratteristiche";
$l_pt_2_1_screenshots1="2.x schermate sezione 1";
$l_pt_2_1_screenshots2="2.x schermate sezione 2";
$l_pt_2_1_screenshots3="2.x schermate sezione 3";
$l_pt_x_x_kdevelop="%s.x info principali";
$l_pt_x_x_announce_kdevelop="%s annuncio rilascio";
$l_pt_x_x_authors="%s.x autori";
$l_pt_x_x_branches_compiling="%s.x Ramo SVN &amp; Compilazione";
$l_pt_x_x_changes="%s.x modifiche";
$l_pt_x_x_faq="%s.x FAQ";
$l_pt_x_x_download="%s.x download";
$l_pt_x_x_features="%s.x caratteristiche";
$l_pt_x_x_kdevelop_po_status="%s.x stato traduzione GUI";
$l_pt_x_x_requirements="%s.x requisiti";
$l_pt_x_x_screenshots="%s.x schermate";
$l_pt_x_x_screenshots1="%s.x schermate sezione 1";
$l_pt_x_x_screenshots2="%s.x schermate sezione 2";
$l_pt_x_x_screenshots3="%s.x schermate sezione 3";
$l_pt_x_x_tutorials="%s.x tutorial";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Tutoriale per Autoconf/Automake";
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI tutorial";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia tutorial";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"User defined settings\" Tutorial";
$l_pt_x_x_ChangeLog="%s.x individual SVN commit logs";
$l_pt_HEAD_kdevelop="HEAD info principali";
$l_pt_HEAD_authors="HEAD autori";
$l_pt_HEAD_branches_compiling="HEAD Ramo SVN &amp; Compilazione";
$l_pt_HEAD_changes="HEAD modifiche";
$l_pt_HEAD_ChangeLog="HEAD individual SVN commit logs";
$l_pt_HEAD_faq="HEAD FAQ";
$l_pt_HEAD_download="HEAD download";
$l_pt_HEAD_features="HEAD caratteristiche";
$l_pt_HEAD_kdevelop_po_status="HEAD stato traduzione GUI";
$l_pt_HEAD_requirements="HEAD requisiti";
$l_pt_HEAD_screenshots="HEAD schermate";
$l_pt_HEAD_screenshots1="HEAD schermate sezione 1";
$l_pt_HEAD_screenshots2="HEAD schermate sezione 2";
$l_pt_HEAD_screenshots3="HEAD schermate sezione 3";
$l_pt_tutorials="tutoriali";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/it/kdevelop/kdevelop/';
