<?php
// kate: encoding iso-8859-1
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'iso-8859-1';

// The php locale, LanguageCode_CountryCode
$l_locale= 'es_ES';

$l_graphic_mode = "Modo Gr&aacute;fico";
$l_text_mode = "Modo Texto";

// Logo
$l_back_kdevelop_home="volver al inicio de KDevelop";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Ingl&eacute;s",
                   "ar" => "Arabico",
                   "cs" => "Checo",
                   "de" => "Alem&aacute;n",
                   "es" => "Espa&ntilde;ol",
                   "fr" => "Franc&eacute;s",
                   "hu" => "Hungaro",
                   "id" => "Indonesio",
                   "it" => "Italiano",
                   "nl" => "Holand&eacute;s",
                   "pt" => "Portugu&eacute;s",
                   "pt_BR" => "Brasile&ntilde;o Portugu&eacute;s",
                   "pl" => "Polaco",
                   "ro" => "Rumano",
                   "ru" => "Ruso",
                   "tr" => "Turco",
                   "uk" => "Ucraniano",
                   "zh_CN" => "Chino Simplificado");

// Google module
$l_search="Buscar";

// Quick downloads module
$l_quick_downloads = "Descargas r&aacute;pidas";
$l_current_stable_version = "Versi&oacute;n estable actual";
$l_current_development_version = "Versi&oacute;n de desarrollo actual";

// Menu module
$l_website_navigation="Navegador del sitio web";
$l_all_versions="todas las versiones";
$l_general="General";
$l_home="Inicio";
$l_versions="Versiones";
$l_features="Funcionalidades";
$l_requirements="Requisitos";
$l_download="Descarga";
$l_cvs_branches_compiling="Ramas de SVN &amp; Compilaci&oacute;n";
$l_changes="Cambios";
$l_bugs_wishes="Bugs &amp; peticiones";

$l_documentation="Documentaci&oacute;n";
$l_user_manual="Manual de Usuario";
$l_api_documentation="Documentaci&oacute;n del API";
$l_platform_api_documentation="Platform API";
$l_tutorials="Tutoriales";
$l_faq="F.A.Q.";
$l_technotes="TechNotes";
$l_mediawiki="Wiki";

$l_presentations_graphics="Presentaciones y Gr&aacute;ficos";
$l_screenshots="Capturas de pantalla";
$l_in_the_press="En la Prensa";
$l_awards="Premios";
$l_logos_banners="Logotipos &amp; Banners";
$l_splashscreens="Pantallas de presentaci&oacute;n";
$l_events="Eventos";

$l_development="Desarrollo";
$l_join_us="¡&Uacute;nase a nosotros!";
$l_current_work_todo_list="Trabajo Actual, lista TODO";
$l_latest_cvs_commits="&Uacute;ltimas entregas en SVN";
$l_browse_code="Navegar por el c&oacute;digo";
$l_web_cvs="SVN Web";
$l_gui_translation="Traducci&oacute;n de la GUI";
$l_user_manual_translation="Traducci&oacute;n del Manual de Usuario";
$l_website_translation="Traducci&oacute;n del Sitio Web";
$l_upload="Upload";

$l_links="Enlaces";
$l_user_progs="Programas de Usuario";
$l_sponsors="Patrocinadores";
$l_donation="Donativo";
$l_development_tools="Herramientas de Desarrollo";

$l_contacts="Contactos";
$l_on_line_chat="Chat en l&iacute;nea";
$l_forum="Foro";
$l_mailinglist="Lista de Correo";
$l_guestbook="Libro de Visitas";
$l_credits="Cr&eacute;ditos";

$l_misc="Miscel&aacute;neo";
$l_license="Licencia";
$l_sitemap="Mapa del sitio web";

// Stats module
$l_user_online = "Usuarios en l&iacute;nea";
$l_visitors_since = "Visitantes desde 22/09/98";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Tabl&oacute;n de discusi&oacute;n</a> de asuntos relacionados con KDevelop, <a href=\"http://www.kde.org/\">KDE</a> y <a href=\"http://www.trolltech.com/\">Qt</a>.";

// IRC module
$l_irc_description="Puede encontrarse con otros usuarios y desarrolladores en el <a href=\"chat/\">canal <em>#kdevelop</em> en <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="El rinc&oacute;n de la imagen";
$l_picture_corner_description="KDevelop 3.0 en modo IDEAl usando KDE 3.2 con el tema Plastik";

// User Programs module
$l_total = "total:";
$l_newest_entries = "las <b>%s</b> entradas m&aacute;s recientes";
$l_by = "por";

// Downloads Per Hour module
$l_downloads_per_hour = "Descargas por hora";

// ChangeLog module
$l_change_log = "Registro de cambios";

// Content module
$l_page_is_outdated = "<b>Esta p&aacute;gina est&aacute; desactualizada</b>, existe una <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">nueva versi&oacute;n en ingl&eacute;s</a>";
$l_translation_by = "Traduci&oacute;n espa&ntilde;ola mantenida por ";
$l_last_updated = "Esta p&aacute;gina ha sido actualizada por &uacute;ltima vez el: ";
$l_website_bugs = "Si hay alg&uacute;n problema con el sitio web, por favor contacte con el ";

// "Other versions" links
$l_other_versions="Otras versiones";
$l_other_news="Otras noticias";
$l_branches_compiling_section_at="Secci&oacute;n de compilaci&oacute;n en";
$l_bugs_section_at="Secci&oacute;n de bugs &amp; peticiones en";
$l_download_section_at="Secci&oacute;n de descargas en";
$l_requirements_section_at="Secci&oacute;n de requisitos en";
$l_tutorials_section_at="Secci&oacute;n de tutoriales en";

// Page titles
$l_pt_main="un Entorno de Desarrollo Integrado - P&aacute;gina de inicio";
$l_pt_main_year="Noticias de %d";
$l_pt_versions="Liberaci&oacute;n de Versiones";
$l_pt_in_the_press="En la Prensa";
$l_pt_license="Licencia";
$l_pt_donate="Donativo y Patrocinadores";
$l_pt_website_translation_status="estado de la traducci&oacute;n del Sitio Web";
$l_pt_optional_files_translation_status="Estado de la traducci&oacute;n del Sitio Web (ficheros opcionales)";
$l_pt_sitemap="Mapa del Sitio Web (sitemap)";
$l_pt_upload="Upload";
$l_pt_current_work="Trabajo actual";
$l_pt_join_the_team="&Uacute;nase a nosotros!";
$l_pt_awards="Premios";
$l_pt_logos_banners="Logotipos &amp; Banners";
$l_pt_pic_corner="Archivo del rinc&oacute;n de la imagen";
$l_pt_splashscreens="Pantallas de presentaci&oacute;n";
$l_pt_users="Programas de usuario";
$l_pt_sponsors="Patrocinadores";
$l_pt_links_development="Enlaces de desarrollo";
$l_pt_links_tools="Herramientas de desarrollo";
$l_pt_mailinglist="Lista de correo";
$l_pt_bugs="Bugs &amp; Peticiones";
$l_pt_stats="Estad&iacute;sticas del sitio Web";
$l_pt_doc_technotes_index="&Iacute;ndice TechNotes";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Archivo del Libro de visitas";
$l_pt_guestbook_guestbook_010203_1999="Libro de visitas Ene/Feb/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Libro de visitas Abr/May/Jun 1999";
$l_pt_guestbook_guestbook_0708_1999="Libro de visitas Jul/Ago 1999";
$l_pt_guestbook_guestbook_091011_1999="Libro de visitas Sep/Oct/Nov 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Libro de visitas Dec/Ene/Feb/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Libro de visitas Abr 2000 / Jul 2004";
$l_pt_events="eventos";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="Informaci&oacute;n principal de 1.x";
$l_pt_1_3_announce_kdevelop_1_3="Anuncio de la liberaci&oacute;n 1.3";
$l_pt_1_3_authors="Autores de la 1.x";
$l_pt_1_3_changes="Cambios de la 1.x";
$l_pt_1_3_features="funcionalidades de la 1.x";
$l_pt_1_3_pressrelease1_0="liberaci&oacute;n en prensa de la 1.0";
$l_pt_1_3_pressrelease1_1="liberaci&oacute;n en prensa de la 1.1";
$l_pt_1_3_screenshots1="Secci&oacute;n 1 de capturas de pantallas de la 1.x";
$l_pt_1_3_screenshots2="Secci&oacute;n 2 de capturas de pantallas de la 1.x";
$l_pt_1_3_screenshots3="Secci&oacute;n 3 de capturas de pantallas de la 1.x";
$l_pt_2_1_kdevelop="Informaci&oacute;n principal de la 2.x";
$l_pt_2_1_announce_kdevelop_2_0="Anuncio de la liberaci&oacute;n 2.0";
$l_pt_2_1_authors="Autores de la 2.x";
$l_pt_2_1_changes="Cambios de la 2.x";
$l_pt_2_1_faq="FAQ de la 2.x";
$l_pt_2_1_features="Funcionalidades de la 2.x";
$l_pt_2_1_screenshots1="Secci&oacute;n 1 de capturas de pantallas de la 2.x";
$l_pt_2_1_screenshots2="Secci&oacute;n 2 de capturas de pantallas de la 2.x";
$l_pt_2_1_screenshots3="Secci&oacute;n 3 de capturas de pantallas de la 2.x";
$l_pt_x_x_kdevelop="Informaci&oacute;n principal de la %s.x";
$l_pt_x_x_announce_kdevelop="Anuncio de la liberaci&oacute;n %s";
$l_pt_x_x_authors="Autores de la %s.x";
$l_pt_x_x_branches_compiling="Ramas &amp; Compilaci&oacute;n de SVN de la %s.x";
$l_pt_x_x_changes="Cambios de la %s.x";
$l_pt_x_x_faq="FAQ de la %s.x";
$l_pt_x_x_download="Descargas de la %s.x";
$l_pt_x_x_features="Funcionalidades de la %s.x";
$l_pt_x_x_kdevelop_po_status="Estado de la traducci&oacute;n de la GUI de la %s.x";
$l_pt_x_x_requirements="Requisitos de la %s.x";
$l_pt_x_x_screenshots="Capturas de pantallas de la %s.x";
$l_pt_x_x_screenshots1="Secci&oacute;n 1 de capturas de pantallas de la %s.x";
$l_pt_x_x_screenshots2="Secci&oacute;n 2 de capturas de pantallas de la %s.x";
$l_pt_x_x_screenshots3="Secci&oacute;n 3 de capturas de pantallas de la %s.x";
$l_pt_x_x_tutorials="Tutoriales de la %s.x";
$l_pt_x_x_doc_tutorial_autoconf="Tutorial de Autoconf/Automake de la %s.x";
$l_pt_x_x_doc_kmditutorial_index="Tutorial de KMDI de la %s.x";
$l_pt_x_x_doc_tutorial_qtopia_index="Tutorial de Qtopia de la %s.x";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"User defined settings\" Tutorial";
$l_pt_x_x_ChangeLog="Logs individuales de commits SVN de la %s.x";
$l_pt_HEAD_kdevelop="Informaci&oacute;n principal de HEAD";
$l_pt_HEAD_authors="Autores de HEAD";
$l_pt_HEAD_branches_compiling="Ramas &amp; Compilaci&oacute;n de SVN de HEAD";
$l_pt_HEAD_changes="Cambios de HEAD";
$l_pt_HEAD_ChangeLog="Logs individuales de commits SVN de HEAD";
$l_pt_HEAD_faq="FAQ de HEAD";
$l_pt_HEAD_download="Descargas de HEAD";
$l_pt_HEAD_features="Funcionalidades de HEAD";
$l_pt_HEAD_kdevelop_po_status="Estado de la traducci&oacute;n de la GUI de HEAD";
$l_pt_HEAD_requirements="Requisitos de HEAD";
$l_pt_HEAD_screenshots="Capturas de pantallas de HEAD";
$l_pt_HEAD_screenshots1="Secci&oacute;n 1 de capturas de pantallas de HEAD";
$l_pt_HEAD_screenshots2="Secci&oacute;n 2 de capturas de pantallas de HEAD";
$l_pt_HEAD_screenshots3="Secci&oacute;n 3 de capturas de pantallas de HEAD";
$l_pt_tutorials="Tutoriales";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
