<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'ar_AE';

$l_graphic_mode = "الواجهة الرسومية";
$l_text_mode = "الواجهة النصية";

// Logo
$l_back_kdevelop_home="عودة إلى الصفحة الرئيسية";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "الانجليزيه",
                   "ar" => "العربية",
                   "cs" => "التشيكيه",
                   "de" => "الالمانيه",
                   "es" => "الاسبانيه",
                   "fr" => "الفرنسية",
                   "hu" => "الهنغاريه",
                   "id" => "الاندونيسيه",
                   "it" => "الايطاليه",
                   "nl" => "الهولنديه",
                   "pt" => "البرتغاليه",
                   "pt_BR" => "البرتغاليه البرازيليه",
                   "pl" => "البولنديه",
                   "ro" => "الرومانيه",
                   "ru" => "الروسي",
                   "tr" => "تركي",
                   "uk" => "الاوكرانى",
                   "zh_CN" => "الصينية المبسطه");

// Google module
$l_search="بحث";

// Quick download module
$l_quick_downloads = "تحميل سريع";
$l_current_stable_version = "الإصدار المستقر الأخير";
$l_current_development_version = "إصدار المطورين الأخير";

// Menu module
$l_website_navigation="تصفح الموقع";
$l_all_versions="جميع الإصدارات";
$l_general="عام";
$l_home="الأولى";
$l_versions="الإصدارات";
$l_features="الميزات";
$l_requirements="متطلبات التشغيل";
$l_download="تحميل";
$l_cvs_branches_compiling="فروع SVN، تفسير";
$l_changes="التغييرات";
$l_bugs_wishes="الأخطاء، الرغبات";

$l_documentation="الوثائق";
$l_user_manual="دليل المستخدم";
$l_api_documentation="وثائق الـ API";
$l_platform_api_documentation="وثائق API بيئة العمل";
$l_tutorials="دروس";
$l_faq="الأسئلة كثيرة التكرار";
$l_technotes="الملاحظات التقنية";
$l_mediawiki="ويكي";

$l_presentations_graphics="العرض والتصميم";
$l_screenshots="صور من البرنامج";
$l_in_the_press="في الصحافة";
$l_awards="جوائز";
$l_logos_banners="الشعارات، البانرات";
$l_splashscreens="شاشات إفتتاحية";
$l_events="أحداث";

$l_development="تطوير";
$l_join_us="إنضم إلينا";
$l_current_work_todo_list="العمل الحالي، أعمال ستنفذ";
$l_latest_cvs_commits="آخر مشاركات SVN";
$l_browse_code="استعرض شيفرة المصدر";
$l_web_cvs="Web SVN";
$l_gui_translation="ترجمة واجهة المستخدم الرسومية";
$l_user_manual_translation="ترجمة دليل الاستخدام";
$l_website_translation="ترجمة الموقع";
$l_upload="رفع";

$l_links="وصلات";
$l_user_progs="برامج المستخدم";
$l_sponsors="الرعاة";
$l_donation="التبرعات";
$l_development_tools="أدوات التطوير";

$l_contacts="اتصل بنا";
$l_on_line_chat="محادثة مباشرة";
$l_forum="المنتدى";
$l_mailinglist="القائمة البريدية";
$l_guestbook="دفتر الزوار";
$l_credits="من نحن";

$l_misc="منوعات";
$l_license="الترخيص";
$l_sitemap="خريطة الموقع";

// Stats module
$l_user_online = "المتصفحون الآن";
$l_visitors_since = "زوار الموقع منذ ٢٢/٩/١٩٩٨";

// ٠.١.٢.٣.٤.٥.٦.٧.٨.٩

// Forum module

//Note From Bassel: 
//I changed the way links work in here because of Arabic language requirments
$l_forum_description="<a href=\"phorum5/\">منتدى النقاش</a> لـ KDevelop, <a href=\"http://www.kde.org/\">KDE</a> and <a href=\"http://www.trolltech.com\">Qt</a> صلات آخرى.";

// IRC module
$l_irc_description="يمكنك إيجاد الكثير من مستخدمي Kdevelop ومطوريه على القناة التالية <a href=\"chat/\"><em>#kdevelop</em> في <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="زاوية الصور";
$l_picture_corner_description="شاهد KDevelop 3.0 على بيئة النوافذ KDE 3.2 مع ثيم Plastik ";

// User Programs module
$l_total = "الإجمالي:";
$l_newest_entries = "الجديد <b>%s</b> موضوع";
$l_by = "أرسل بواسطة";

// Downloads Per Hour module
$l_downloads_per_hour = "عدد مرات التحميل بالساعة";

// ChangeLog module
$l_change_log = "دليل التغييرات";

// Content module
$l_page_is_outdated = "<b>لقد إنتهت صلاحية هذه الصفحة</b>, يوجد نسخة أحدث <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">باللغة الإنكليزية</a> ";
$l_translation_by = "قامت بمتابعة الترجمة الإنكليزية: ";
$l_last_updated = "آخر تحديث لهذه الصفحة: ";
$l_website_bugs = "اذا واجهتك أي مشكلة في هذا الموقع الرجاء الاتصال بـ  ";

// "Other versions" links
$l_other_versions="إصدارات أخرى";
$l_other_news="أخبار أخرى";
$l_branches_compiling_section_at="قسم الـ Compile في";
$l_bugs_section_at="قسم الأخطاء، الرغبات في";
$l_download_section_at="قسم التحميل في";
$l_requirements_section_at="متطلبات التشغيل في";
$l_tutorials_section_at="الدروس التعليمية في";


// ٠.١.٢.٣.٤.٥.٦.٧.٨.٩

// Page titles
$l_pt_main="بيئة تطوير مدمجة - الصفحة الرئيسية";
$l_pt_main_year="أخبار %d";
$l_pt_versions="الإصدارات المستقرة";
$l_pt_in_the_press="في الصحافة";
$l_pt_license="الترخيص";
$l_pt_donate="التبرعات والرعاية";
$l_pt_website_translation_status="جدول متابعة ترجمة الموقع";
$l_pt_optional_files_translation_status="جدول متابعة ترجمة الموقع ( ملفات إختيارية )";
$l_pt_sitemap="خريطة الموقع";
$l_pt_upload="رفع الملفات";
$l_pt_current_work="العمل الحالي";
$l_pt_join_the_team="إنضم إلينا!";
$l_pt_awards="الجوائز";
$l_pt_logos_banners="اللوغو، والبانرات";
$l_pt_pic_corner="أرشيف زاوية الصور";
$l_pt_splashscreens="شاشات إفتتاحية";
$l_pt_users="برامج المستخدم";
$l_pt_sponsors="الرعاية";
$l_pt_links_development="وصلات التطوير";
$l_pt_links_tools="أدوات التطوير";
$l_pt_mailinglist="القائمة البريدية";
$l_pt_bugs="الأخطاء، الرغبات";
$l_pt_stats="إحصائيات الموقع";
$l_pt_doc_technotes_index="فهرس الملاحظات التقنية";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="أرشيف دفتر الزوار";
$l_pt_guestbook_guestbook_010203_1999="دفتر الزوار كانون الثاني/شباط/آذار ١٩٩٩";
$l_pt_guestbook_guestbook_040506_1999="دفتر الزوار نيسان/أيار/حزيران ١٩٩٩";
$l_pt_guestbook_guestbook_0708_1999="دفتر الزوار تموز/آب ١٩٩٩";
$l_pt_guestbook_guestbook_091011_1999="دفتر الزوار أيلول/تشرين الأول/تشرين الثاني ١٩٩٩";
$l_pt_guestbook_guestbook_12_03_1999_2000="دفتر الزوار كانون الأول/كانون الثاني/شباط/آذار ١٩٩٩/٢٠٠٠";
$l_pt_guestbook_guestbook_2000_2004="دفتر الزوار نيسان ٢٠٠٠ / تموز ٢٠٠٤";
$l_pt_events="الأحداث";
$l_pt_events_linuxtag2000="Linuxtag ٢٠٠٠";
$l_pt_events_linuxtag2001="Linuxtag ٢٠٠١";
$l_pt_events_kastle2003="Kastle ٢٠٠٣";
$l_pt_events_akademy2004="Akademy ٢٠٠٤";
$l_pt_events_akademy2006="Akademy ٢٠٠٦";
$l_pt_1_3_kdevelop="1.x المعلومات الرئيسية";
$l_pt_1_3_announce_kdevelop_1_3="1.3 اعلانات الاصدار";
$l_pt_1_3_authors="1.x المبرمجون المساهمون";
$l_pt_1_3_changes="1.x التغييرات";
$l_pt_1_3_features="1.x الميزات";
$l_pt_1_3_pressrelease1_0="1.0 الموقع في الصحف";
$l_pt_1_3_pressrelease1_1="1.1 الموقع في الصحف";
$l_pt_1_3_screenshots1="1.x لقطات من البرنامج -- الجزء 1";
$l_pt_1_3_screenshots2="1.x لقطات من البرنامج -- الجزء 2";
$l_pt_1_3_screenshots3="1.x لقطات من البرنامج -- الجزء 3";
$l_pt_2_1_kdevelop="2.x المعلومات الرئيسية";
$l_pt_2_1_announce_kdevelop_2_0="2.0 اعلانات الاصدار";
$l_pt_2_1_authors="2.x المبرمجون المساهمون";
$l_pt_2_1_changes="2.x التغييرات";
$l_pt_2_1_faq="2.x الأسئلة كثيرة التكرار";
$l_pt_2_1_features="2.x الميزات";
$l_pt_2_1_screenshots1="2.x لقطات من البرنامج -- الجزء 1";
$l_pt_2_1_screenshots2="2.x لقطات من البرنامج -- الجزء 2";
$l_pt_2_1_screenshots3="2.x لقطات من البرنامج -- الجزء 3";
$l_pt_x_x_kdevelop="%s.x المعلومات الرئيسية";
$l_pt_x_x_announce_kdevelop="%s اعلانات الاصدار";
$l_pt_x_x_authors="%s.x المبرمجون المساهمون";
$l_pt_x_x_branches_compiling="%s.x SVN فروع&amp; Compiling";
$l_pt_x_x_changes="%s.x التغييرات";
$l_pt_x_x_faq="%s.x الأسئلة كثيرة التكرار";
$l_pt_x_x_download="%s.x تحميل";
$l_pt_x_x_features="%s.x الميزات";
$l_pt_x_x_kdevelop_po_status="%s.x حالة ترجمة واجهة البرنامج";
$l_pt_x_x_requirements="%s.x المتطلبات";
$l_pt_x_x_screenshots="%s.x لقطات من البرنامج";
$l_pt_x_x_screenshots1="%s.x لقطات من البرنامج -- الجزء 1";
$l_pt_x_x_screenshots2="%s.x لقطات من البرنامج -- الجزء 2";
$l_pt_x_x_screenshots3="%s.x لقطات من البرنامج -- الجزء 3";
$l_pt_x_x_tutorials="%s.x دروس";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Autoconf/Automake دروس ال"; 
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI دروس ال";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia دروس ال";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"User defined settings\" دروس ال";
$l_pt_x_x_ChangeLog="%s.x  SVN قائمة مفصلة لتغييرات";
$l_pt_HEAD_kdevelop="HEAD المعلومات الرئيسية";
$l_pt_HEAD_authors="HEAD المبرمجون المساهمون";
$l_pt_HEAD_branches_compiling="HEAD SVN فروع &amp; Compiling";
$l_pt_HEAD_changes="HEAD التغييرات";
$l_pt_HEAD_ChangeLog="HEAD SVN قائمة مفصلة لتغييرات";
$l_pt_HEAD_faq="HEAD الأسئلة كثيرة التكرار";
$l_pt_HEAD_download="HEAD تحميل";
$l_pt_HEAD_features="HEAD الميزات";
$l_pt_HEAD_kdevelop_po_status="HEAD حالة ترجمة واجهة البرنامج";
$l_pt_HEAD_requirements="HEAD المتطلبات";
$l_pt_HEAD_screenshots="HEAD لقطات من البرنامج";
$l_pt_HEAD_screenshots1="HEAD لقطات من البرنامج -- الجزء 1";
$l_pt_HEAD_screenshots2="HEAD لقطات من البرنامج -- الجزء 2";
$l_pt_HEAD_screenshots3="HEAD لقطات من البرنامج -- الجزء 3";
$l_pt_tutorials="دروس";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
