<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'hu_HU';

$l_graphic_mode = "Grafikus mód";
$l_text_mode = "Szöveges mód";

// Logo
$l_back_kdevelop_home="Vissza a KDevelop kezdőoldalra";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Angol",
                   "ar" => "Arab",
                   "cs" => "Cseh",
                   "de" => "Német",
                   "es" => "Spanyol",
                   "fr" => "Francia",
                   "hu" => "Magyar",
                   "id" => "Indonéz",
                   "it" => "Olasz",
                   "nl" => "Holland",
                   "pt" => "Portugál",
                   "pt_BR" => "Brazíliai portugál",
                   "pl" => "Lengyel",
                   "ro" => "Román",
                   "ru" => "Orosz",
                   "tr" => "Török",
                   "uk" => "Ukrán",
                   "zh_CN" => "Egyszerűsített kínai");

$l_more_elipsis = 'több ...';

$l_what_is_KDevelop = 'Mi a KDevelop ?';
$l_def_KDevelop = 'egy szabad, nyílt forráskódú fejlesztési környezet (IDE) MS Windowsra, Mac OS X-re, Linuxra, Solarisra és FreeBSDre.
Funkciókban gazdag, pluginok által bővíthető fejlesztési környezet C/C++ és más programozási nyelvek számára.
Alapja a KDevPlatform, valamint a KDE és Qt készletek. 1998 óta áll fejlesztés alatt.';
$l_def_KDevPlatform = 'egy szabad, nyílt forráskódú fejlesztői készletcsoport (library), amely IDE-szerű programok alapjául szolgálhat.
Programozási nyelv-független, és olyan programok használatára tervezett, mint a KDevelop, Quanta, Kile, KTechLab stb.';
$l_def_KDevelop4 = 'Egy Qt4/KDE4-re alapozott fontos újraírás, erős nyelvarchitektúrával. Erőteljes fejlesztés alatt áll, jelenleg béta állapotban van. C++ és PHP fejlesztéshez ajánlott. Linuxra ajánlott (<b>a többi rendszeren is működhe
t</b>, de még nincs tesztelve).';
$l_def_KDevelop3 = 'Igen stabil és érett Qt3/KDE3-alapú IDE sok programozási nyelvhez. Már nincs fejlesztés alatt.';

// cvsbranches.ihtml page
$l_unstable_development = 'instabil fejlesztés %s részére';
$l_stable_version = 'stabil %s részére';
$l_entirely_new_code = 'teljesen új alapkód, nulláról újraírt';
$l_was_released_with = 'ezzel volt kiadva:';
$l_bugfix_versions = 'változatai';
$l_scheduled_for_versions = 'verzióhoz tervezett';
$l_scheduled_versions = '%s hibajavító %s %s-szel együtt lesznek kiadva';
$l_release_schedule = '%s kiadási idővonala';

// Google module
$l_search="Keresés";

// Quick download module
$l_quick_downloads = "Gyors letöltés";
$l_current_stable_version = "Aktuális stabil kiadás";
$l_current_development_version = "Aktuális fejlesztői kiadás";

// Menu module
$l_website_navigation="Oldal navigáció";
$l_all_versions="minden&nbsp;kiadás";
$l_general="Általános";
$l_home="Kezdőoldal";
$l_versions="Kiadások";
$l_features="Funkciók";
$l_requirements="Rendszerkövetelmémyek";
$l_download="Letöltés";
$l_cvs_branches_compiling="SVN ágak &amp; fordítás";
$l_changes="Változások";
$l_bugs_wishes="Hibák &amp; kívánságok";

$l_documentation="Dokumentáció";
$l_user_manual="Kézikönyv";
$l_api_documentation="API dokumentáció";
$l_platform_api_documentation="Platform API";
$l_tutorials="Leckék";
$l_faq="GY.I.K.";
$l_technotes="Technikai adatok";
$l_mediawiki="Wiki";

$l_presentations_graphics="Bemutatók és grafikák";
$l_screenshots="Képernyőfotók";
$l_in_the_press="Média";
$l_awards="Kitűntetések";
$l_logos_banners="Logók &amp; bannerek";
$l_splashscreens="Nyitóképek";
$l_events="Események";

$l_development="Fejlesztés";
$l_join_us="Csatlakozz!";
$l_current_work_todo_list="Jelenlegi munka, tennivalók listája";
$l_latest_cvs_commits="Legutóbbi SVN bejegyzések";
$l_browse_code="Forráskód böngészése";
$l_web_cvs="Web SVN";
$l_gui_translation="GUI fordítás";
$l_user_manual_translation="Kézikönyv fordítás";
$l_website_translation="Weboldal fordítás";
$l_upload="Feltöltés";

$l_links="Linkek";
$l_user_progs="Felhasználói programok";
$l_sponsors="Támogatók";
$l_donation="Adomány";
$l_development_tools="Fejlesztőeszközök";

$l_contacts="Kapcsolat";
$l_on_line_chat="On-line chat";
$l_forum="Fórum";
$l_mailinglist="Levelezőlista";
$l_guestbook="Vendégkönyv";
$l_credits="Közremuködők";

$l_misc="Egyéb";
$l_license="Licensz";
$l_sitemap="Oldaltérkép";

// Stats module
$l_user_online = "Felhasználó online";
$l_visitors_since = "Látogatók 1998.09.22. óta";

// Forum module
$l_forum_description="<a href=\"phorum5/\">board</a> KDevelop, <a href=\"http://www.kde.org/\">KDE</a> és <a href=\"http://www.trolltech.com\">Qt</a> témájú társalgás.";

// IRC module
$l_irc_description="Felhasználókkal és fejlesztőkkel a <a href=\"chat/\"><em>#kdevelop</em> csatornán, az <em>irc.kde.org</em></a> szerveren találkozhatsz.";

// Picture Corner module
$l_picture_corner="Képsarok";
$l_picture_corner_description="KDevelop 3.0 IDEAl módban, KDE 3.2 alatt, Plastik témával.";

// User Programs module
$l_total = "Összesen:";
$l_newest_entries = "Legújabb <b>%s</b> bejegyzések";
$l_by = "by";

// Downloads Per Hour module
$l_downloads_per_hour = "Letöltések óránként";

// ChangeLog module
$l_change_log = "Változások";

// Content module
$l_page_is_outdated = "<b>Ez az oldal elavult</b>, újabb<a href=\"index.html?filename=$filename&amp;set_lang=hu\" hreflang=\"hu\">magyar változata</a> létezik";
$l_translation_by = "Magyar fordítás karbantartója ";
$l_last_updated = "Az oldal utolsó frissítése: ";
$l_website_bugs = "Amennyiben problémád akad az oldallal kapcsoladban, a következő személy(eke)t keresd ";
$l_latest_blog_posts = "KDevelop fejlesztők utolsó blogkifüggesztései";

// "Other versions" links
$l_other_versions="Más kiadások";
$l_other_news="Más hírek";
$l_branches_compiling_section_at="Fordítási szekció itt";
$l_bugs_section_at="Hibák &amp; kívánságok szekció itt";
$l_download_section_at="Letöltési szekció itt";
$l_requirements_section_at="Kérések szekció itt";
$l_tutorials_section_at="Leckék szekció itt";

// Page titles
$l_pt_main="Integrált Fejlesztői Környezet - Honlap";
$l_pt_main_year="%d-es hírek";
$l_pt_versions="Kiadások";
$l_pt_in_the_press="Sajtó";
$l_pt_license="Licensz";
$l_pt_donate="Adományok és Támogatás";
$l_pt_website_translation_status="Weboldal-fordítás állapota";
$l_pt_optional_files_translation_status="Weboldal-fordítás állapota (opcionális fájlok)";
$l_pt_sitemap="Weblaptérkép (oldaltérkép)";
$l_pt_upload="Feltöltés";
$l_pt_current_work="Jelenlegi munka";
$l_pt_join_the_team="Csatlakozz!";
$l_pt_awards="Kitüntetések";
$l_pt_logos_banners="Logók &amp; bannerek";
$l_pt_pic_corner="Képsarok archívum";
$l_pt_splashscreens="Nyitóképek";
$l_pt_users="Felhasználói programok";
$l_pt_sponsors="Támogatók";
$l_pt_links_development="Fejlesztői hivatkozások";
$l_pt_links_tools="Fejlesztői eszközök";
$l_pt_mailinglist="Levelezőlista";
$l_pt_bugs="Hibák &amp; kívánságok";
$l_pt_stats="Weboldal statisztikák";
$l_pt_doc_technotes_index="Technikai információk indexe";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Vendégkönyv archívum";
$l_pt_guestbook_guestbook_010203_1999="Vendégkönyv 1999. Jan/Feb/Márc";
$l_pt_guestbook_guestbook_040506_1999="Vendégkönyv 1999. Ápr/May/Jún";
$l_pt_guestbook_guestbook_0708_1999="Vendégkönyv 1999. Júl/Aug";
$l_pt_guestbook_guestbook_091011_1999="Vendégkönyv 1999. Szept/Okt/Nov";
$l_pt_guestbook_guestbook_12_03_1999_2000="Vendégkönyv 1999/2000. Dec/Jan/Feb/Márc";
$l_pt_guestbook_guestbook_2000_2004="Vendégkönyv 2000. Ápr / 2004. Júl";
$l_pt_events="események";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x fobb információk";
$l_pt_1_3_announce_kdevelop_1_3="1.3 kiadási értesíto";
$l_pt_1_3_authors="1.x szerzők";
$l_pt_1_3_changes="1.x változások";
$l_pt_1_3_features="1.x funkciók";
$l_pt_1_3_pressrelease1_0="1.0 sajtóanyag";
$l_pt_1_3_pressrelease1_1="1.1 sajtóanyag";
$l_pt_1_3_screenshots1="1.x képernyőképek 1";
$l_pt_1_3_screenshots2="1.x képernyőképek 2";
$l_pt_1_3_screenshots3="1.x képernyőképek 3";
$l_pt_2_1_kdevelop="2.x főbb információk";
$l_pt_2_1_announce_kdevelop_2_0="2.0 kiadási értesítő";
$l_pt_2_1_authors="2.x szerzők";
$l_pt_2_1_changes="2.x változások";
$l_pt_2_1_faq="2.x GYIK";
$l_pt_2_1_features="2.x funkciók";
$l_pt_2_1_screenshots1="2.x képernyőképek 1";
$l_pt_2_1_screenshots2="2.x képernyőképek 2";
$l_pt_2_1_screenshots3="2.x képernyőképek 3";
$l_pt_x_x_kdevelop="%s.x főbb információk";
$l_pt_x_x_announce_kdevelop="%s kiadási értesítő";
$l_pt_x_x_authors="%s.x szerzők";
$l_pt_x_x_branches_compiling="%s.x SVN ágak &amp; fordítás";
$l_pt_x_x_changes="%s.x változások";
$l_pt_x_x_faq="%s.x GYIK";
$l_pt_x_x_download="%s.x letöltés";
$l_pt_x_x_features="%s.x funkciók";
$l_pt_x_x_kdevelop_po_status="%s.x GUI fordítás állapota";
$l_pt_x_x_requirements="%s.x rendszerkövetelmények";
$l_pt_x_x_screenshots="%s.x képernyőképek";
$l_pt_x_x_screenshots1="%s.x képernyőképek 1";
$l_pt_x_x_screenshots2="%s.x képernyőképek 2";
$l_pt_x_x_screenshots3="%s.x képernyőképek 3";
$l_pt_x_x_tutorials="%s.x leckék";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Autoconf/Automake lecke";
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI lecke";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia lecke";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"Felhasználói beállítások\" lecke";
$l_pt_x_x_ChangeLog="%s.x egyéni SVN commit naplók";
$l_pt_HEAD_kdevelop="HEAD főbb információk";
$l_pt_HEAD_authors="HEAD szerzők";
$l_pt_HEAD_branches_compiling="HEAD SVN ágak &amp; fordítás";
$l_pt_HEAD_changes="HEAD változások";
$l_pt_HEAD_ChangeLog="HEAD egyéni SVN commit naplók";
$l_pt_HEAD_faq="HEAD GYIK";
$l_pt_HEAD_download="HEAD letöltés";
$l_pt_HEAD_features="HEAD funkciók";
$l_pt_HEAD_kdevelop_po_status="HEAD GUI fordítás állapota";
$l_pt_HEAD_requirements="HEAD rendszerkövetelmények";
$l_pt_HEAD_screenshots="HEAD képernyőképek";
$l_pt_HEAD_screenshots1="HEAD képernyőképek 1";
$l_pt_HEAD_screenshots2="HEAD képernyőképek 2";
$l_pt_HEAD_screenshots3="HEAD képernyőképek 3";
$l_pt_tutorials="leckék";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
