<?php
// kate: encoding iso-8859-1
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'iso-8859-1';

// The php locale, LanguageCode_CountryCode
$l_locale= 'pt_BR';

$l_graphic_mode = "Modo Gr&aacute;fico";
$l_text_mode = "Modo Texto";

// Logo
$l_back_kdevelop_home="Retornar &agrave; P&aacute;gina Inicial do KDevelop";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Ingl&ecirc;s",
                   "ar" => "Arabe",
                   "cs" => "Tcheco",
                   "de" => "Alem&atilde;o",
                   "es" => "Espanhol",
                   "fr" => "Franc&ecirc;s",
                   "hu" => "Hungaro",
                   "id" => "Indonesio",
                   "it" => "Italiano",
                   "nl" => "Holand&ecirc;s",
                   "pt" => "Portugu&ecirc;s",
                   "pt_BR" => "Portugu&ecirc;s do Brasil",
                   "pl" => "Polon&ecirc;s",
                   "ro" => "Romeno",
                   "ru" => "Russo",
                   "tr" => "Turco",
                   "uk" => "Ucraniano",
                   "zh_CN" => "Chin&ecirc;s simplificado");

// Google module
$l_search="Pesquisa";

// Quick downloads module
$l_quick_downloads = "Download direto";
$l_current_stable_version = "Vers&atilde;o est&aacute;vel atual";
$l_current_development_version = "Vers&atilde;o atual em desenvolvimento";

// Menu module
$l_website_navigation="Navega&ccedil;&atilde;o pela P&aacute;gina";
$l_all_versions="todas&nbsp;vers&otilde;es";
$l_general="Geral";
$l_home="P&aacute;gina Principal";
$l_versions="Vers&otilde;es";
$l_features="Caracter&iacute;sticas";
$l_requirements="Requisitos";
$l_download="Download";
$l_cvs_branches_compiling="Ramos SVN & Compila&ccedil;&atilde;o";
$l_changes="Mudan&ccedil;as";
$l_bugs_wishes="Bugs &amp; Sugest&otilde;es";

$l_documentation="Documenta&ccedil;&atilde;o";
$l_user_manual="Manual do Usu&aacute;rio";
$l_api_documentation="Documenta&ccedil;&atilde;o API";
$l_platform_api_documentation="Platform API";
$l_tutorials="Tutoriais";
$l_faq="F.A.Q.";
$l_technotes="Notas Técnicas";
$l_mediawiki="Wiki";

$l_presentations_graphics="Apresenta&ccedil;&otilde;es e Gr&aacute;ficos";
$l_screenshots="Telas Capturadas";
$l_in_the_press="Na imprensa";
$l_awards="Pr&ecirc;mios";
$l_logos_banners="Logotipos &amp; Distintivos";
$l_splashscreens="Telas de Abertura";
$l_events="Eventos";

$l_development="Devolvimento";
$l_join_us="Junte-se a n&oacute;s!";
$l_current_work_todo_list="Tarefas em andamento";
$l_latest_cvs_commits="Atualiza&ccedil;&otilde;es mais recentes do SVN";
$l_browse_code="Navegar pelo c&oacute;digo-fonte";
$l_web_cvs="Web SVN";
$l_gui_translation="Tradu&ccedil;&otilde;es da GUI ";
$l_user_manual_translation="Tradu&ccedil;&otilde;es do Manual do Usu&aacute;rio";
$l_website_translation="Tradu&ccedil;&otilde;es do Site";
$l_upload="Upload";

$l_links="Links";
$l_user_progs="Programas dos Usu&aacute;rios";
$l_sponsors="Patrocinadores";
$l_donation="Doa&ccedil;&otilde;es";
$l_development_tools="Ferramentas de Desevolvimento";

$l_contacts="Contatos";
$l_on_line_chat="Chat on-line";
$l_forum="F&oacute;rum";
$l_mailinglist="Lista de Discuss&atilde;o";
$l_guestbook="Livro de Visitas";
$l_credits="Cr&eacute;ditos";

$l_misc="Diversos";
$l_license="Licen&ccedil;a";
$l_sitemap="Mapa do Site";

// Stats module
$l_user_online = "Usu&aacute;rios On-Line";
$l_visitors_since = "Visitantes desde 22/09/98";

// Forum module
$l_forum_description="<a href=\"phorum5/\">F&oacute;rum de debate</a> de temas relacionados ao KDevelop, <a href=\"http://www.kde.org/\">KDE</a> e <a href=\"http://www.trolltech.com\">Qt</a>.";

// IRC module
$l_irc_description="Voc&ecirc; pode encontrar outros usu&aacute;rios e desenvolvedores no <a href=\"chat/\">canal <em>#kdevelop</em> em <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Picture Corner";
$l_picture_corner_description="KDevelop 3.0 no modo IDEAl utilizando KDE 3.2 com o tema Plastik";

// User Programs module
$l_total = "total:";
$l_newest_entries = "ùltimas <b>%s</b> entradas";
$l_by = "por";

// Downloads Per Hour module
$l_downloads_per_hour = "Downloads por hora";

// ChangeLog module
$l_change_log = "ChangeLog";

// Content module
$l_page_is_outdated = "<b>Esta p&aacute;gina est&aacute; desatualizada</b>, existe uma vers&atilde;o mais recente  <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">em ingl&ecirc;s</a>";
$l_translation_by = "Tradu&ccedil;&atilde;o Portugu&ecirc;s do Brasil mantida por ";
$l_last_updated = "Esta p&aacute;gina foi atualizada em: ";
$l_website_bugs = "Se tiver problemas com esta p&aacute;gina, por favor contate o  ";

// "Other versions" links
$l_other_versions="Outras vers&otilde;es";
$l_other_news="Outra not&iacute;cias";
$l_branches_compiling_section_at="Se&ccedil;&atilde;o de compila&ccedil;&atilde;o em";
$l_bugs_section_at="Se&ccedil;&atilde;o de erros &amp; sugest&otilde;es em";
$l_download_section_at="Se&ccedil;&atilde;o de download em";
$l_requirements_section_at="Se&ccedil;&atilde;o de pre-requisitos em";
$l_tutorials_section_at="Se&ccedil;&atilde;o de tutoriais em";

// Page titles
$l_pt_main="um Ambiente Integrado de Desenvolvimento (IDE) - P&aacute;gina Principal";
$l_pt_main_year="Not&iacute;cias de %d";
$l_pt_versions="Vers&otilde;es lan&ccedil;adas";
$l_pt_in_the_press="Na imprensa";
$l_pt_license="Licen&ccedil;a";
$l_pt_donate="Doa&ccedil;&otilde;es e patroc&iacute;nio";
$l_pt_website_translation_status="Status da tradu&ccedil;&atilde;o do website";
$l_pt_optional_files_translation_status="Status da tradu&ccedil;&atilde;o do website (arquivos opcionais)";
$l_pt_sitemap="Mapa do site";
$l_pt_upload="Upload";
$l_pt_current_work="Trabalhos em andamento";
$l_pt_join_the_team="Junte-se a n&oacute;s!";
$l_pt_awards="Pr&ecirc;mios";
$l_pt_logos_banners="Logotipos &amp; Distintivos";
$l_pt_pic_corner="Arquivo do cantinho das figuras";
$l_pt_splashscreens="Telas de abertura";
$l_pt_users="Programas dos usu&aacute;rios";
$l_pt_sponsors="Patrocinadores";
$l_pt_links_development="Links de desenvolvimento";
$l_pt_links_tools="Ferramentas de Desevolvimento";
$l_pt_mailinglist="Lista de discuss&atilde;o";
$l_pt_bugs="Bugs &amp; Sugest&otilde;es";
$l_pt_stats="Estat&iacute;sticas do site";
$l_pt_doc_technotes_index="Índice das notas técnicas";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Arquivos do livro de visitas";
$l_pt_guestbook_guestbook_010203_1999="Livro de visitas Jan/Fev/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Livro de visitas Abr/Mai/Jun 1999";
$l_pt_guestbook_guestbook_0708_1999="Livro de visitas Jul/Ago 1999";
$l_pt_guestbook_guestbook_091011_1999="Livro de visitas Set/Out/Nov 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Livro de visitas Dez/Jan/Fev/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Livro de visitas Abr 2000 / Jul 2004";
$l_pt_events="eventos";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="Informa&ccedil;&otilde;es principais da vers&atilde;o 1.x";
$l_pt_1_3_announce_kdevelop_1_3="An&uacute;ncio de lan&ccedil;amento da vers&atilde;o 1.3";
$l_pt_1_3_authors="Autores da vers&atilde;o 1.x";
$l_pt_1_3_changes="Modifica&ccedil;&otilde;es da vers&atilde;o 1.x";
$l_pt_1_3_features="Caracter&iacute;sticas da vers&atilde;o 1.x";
$l_pt_1_3_pressrelease1_0="Lan&ccedil;amento na imprensa da vers&atilde;o 1.0";
$l_pt_1_3_pressrelease1_1="Lan&ccedil;amento na imprensa da vers&atilde;o 1.1";
$l_pt_1_3_screenshots1="Telas capturadas da vers&atilde;o 1.x - se&ccedil;&atilde;o 1";
$l_pt_1_3_screenshots2="Telas capturadas da vers&atilde;o 1.x - se&ccedil;&atilde;o 2";
$l_pt_1_3_screenshots3="Telas capturadas da vers&atilde;o 1.x - se&ccedil;&atilde;o 3";
$l_pt_2_1_kdevelop="Informa&ccedil;&otilde;es principais da vers&atilde;o 2.x";
$l_pt_2_1_announce_kdevelop_2_0="An&uacute;ncio de lan&ccedil;amento da vers&atilde;o 2.0";
$l_pt_2_1_authors="Autores da vers&atilde;o 2.x";
$l_pt_2_1_changes="Modifica&ccedil;&otilde;es da vers&atilde;o 2.x";
$l_pt_2_1_faq="Perguntas freq&uuml;entes da vers&atilde;o 2.x";
$l_pt_2_1_features="Caracter&iacute;sticas da vers&atilde;o 2.x";
$l_pt_2_1_screenshots1="Telas capturadas da vers&atilde;o 2.x - se&ccedil;&atilde;o 1";
$l_pt_2_1_screenshots2="Telas capturadas da vers&atilde;o 2.x - se&ccedil;&atilde;o 2";
$l_pt_2_1_screenshots3="Telas capturadas da vers&atilde;o 2.x - se&ccedil;&atilde;o 3";
$l_pt_x_x_kdevelop="Informa&ccedil;&otilde;es principais da vers&atilde;o %s.x";
$l_pt_x_x_announce_kdevelop="An&uacute;ncio de lan&ccedil;amento da vers&atilde;o %s";
$l_pt_x_x_authors="Autores da vers&atilde;o %s.x";
$l_pt_x_x_branches_compiling="Ramos SVN e Compila&ccedil;&atilde;o da vers&atilde;o %s.x";
$l_pt_x_x_changes="Modifica&ccedil;&otilde;es da vers&atilde;o %s.x";
$l_pt_x_x_faq="Perguntas freq&uuml;entes %s.x";
$l_pt_x_x_download="Download da vers&atilde;o %s.x";
$l_pt_x_x_features="Caracter&iacute;sticas da vers&atilde;o %s.x";
$l_pt_x_x_kdevelop_po_status="Status de tradu&ccedil;&atilde;o da vers&atilde;o %s.x GUI";
$l_pt_x_x_requirements="Pre-requisitos da vers&atilde;o %s.x";
$l_pt_x_x_screenshots="Telas capturadas da vers&atilde;o %s.x";
$l_pt_x_x_screenshots1="Telas capturadas da vers&atilde;o %s.x - se&ccedil;&atilde;o 1";
$l_pt_x_x_screenshots2="Telas capturadas da vers&atilde;o %s.x - se&ccedil;&atilde;o 2";
$l_pt_x_x_screenshots3="Telas capturadas da vers&atilde;o %s.x - se&ccedil;&atilde;o 3";
$l_pt_x_x_tutorials="Tutoriais da vers&atilde;o %s.x";
$l_pt_x_x_doc_tutorial_autoconf="Tutorial autoconf/automake da vers&atilde;o %s.x "; 
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI tutorial";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia tutorial";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"User defined settings\" Tutorial";
$l_pt_x_x_ChangeLog="SVN commit logs individuais da vers&atilde;o %s.x";
$l_pt_HEAD_kdevelop="Informa&ccedil;&otilde;es principais da vers&atilde;o HEAD";
$l_pt_HEAD_authors="Autores da vers&atilde;o HEAD";
$l_pt_HEAD_branches_compiling="Ramos SVN e Compila&ccedil;&atilde;o da vers&atilde;o HEAD";
$l_pt_HEAD_changes="Modifica&ccedil;&otilde;es da vers&atilde;o HEAD";
$l_pt_HEAD_ChangeLog="SVN commit logs individuais da vers&atilde;o HEAD";
$l_pt_HEAD_faq="Perguntas freq&uuml;entes da vers&atilde;o HEAD";
$l_pt_HEAD_download="Download da vers&atilde;o HEAD";
$l_pt_HEAD_features="Caracter&iacute;sticas da vers&atilde;o HEAD";
$l_pt_HEAD_kdevelop_po_status="Status de tradu&ccedil;&atilde;o da GUI da vers&atilde;o HEAD";
$l_pt_HEAD_requirements="Pre-requisitos da vers&atilde;o HEAD";
$l_pt_HEAD_screenshots="Telas capturadas da vers&atilde;o HEAD";
$l_pt_HEAD_screenshots1="Telas capturadas da vers&atilde;o HEAD - se&ccedil;&atilde;o 1";
$l_pt_HEAD_screenshots2="Telas capturadas da vers&atilde;o HEAD - se&ccedil;&atilde;o 2";
$l_pt_HEAD_screenshots3="Telas capturadas da vers&atilde;o HEAD - se&ccedil;&atilde;o 3";
$l_pt_tutorials="Tutoriais";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/pt/kdevelop/kdevelop/';
