<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'uk_UA';

$l_graphic_mode = "Графічний режим";
$l_text_mode = "Текстовий режим";

// Logo
$l_back_kdevelop_home="повернутися до початкової сторінки";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Англійська",
                   "ar" => "Arabic",
                   "cs" => "Чеська",
                   "de" => "Німецька",
                   "es" => "Іспанська",
                   "fr" => "Французська",
                   "hu" => "Hungarian",
                   "id" => "Індонезійська",
                   "it" => "Італійська",
                   "nl" => "Голандська",
                   "pt" => "Португальська",
                   "pt_BR" => "Бразильська португальська",
                   "pl" => "Польська",
                   "ro" => "Румунська",
                   "ru" => "Російська",
                   "tr" => "Турецька",
                   "uk" => "Українська",
                   "zh_CN" => "Спрощена китайська");

// Google module
$l_search="Пошук";

// Quick download module
$l_quick_downloads = "Швидке завантаження";
$l_current_stable_version = "Поточна стабільна версія";
$l_current_development_version = "Версія у розробці";

// Menu module
$l_website_navigation="Навігація по сайту";
$l_all_versions="всі&nbsp;версії";
$l_general="Загальне";
$l_home="Початкова сторінка";
$l_versions="Версії";
$l_features="Можливості";
$l_requirements="Вимоги";
$l_download="Завантаження";
$l_cvs_branches_compiling="Гілки SVN та компіляція";
$l_changes="Зміни";
$l_bugs_wishes="Помилки та побажання";

$l_documentation="Документація";
$l_user_manual="Підручник користувача";
$l_api_documentation="Документація по API";
$l_platform_api_documentation="Platform API";
$l_tutorials="Посібники";
$l_faq="F.A.Q.";
$l_technotes="TechNotes";
$l_mediawiki="Wiki";

$l_presentations_graphics="Презентації та графіка";
$l_screenshots="Знімки екрану";
$l_in_the_press="В пресі";
$l_awards="Нагороди";
$l_logos_banners="Логотипи та банери";
$l_splashscreens="Заставки";
$l_events="Події";

$l_development="Розробка";
$l_join_us="Приєднуйтесь до нас!";
$l_current_work_todo_list="Поточна робота, список TODO";
$l_latest_cvs_commits="Останні зміни в SVN";
$l_browse_code="Перегляд коду";
$l_web_cvs="Web SVN";
$l_gui_translation="Переклад інтерфейсу";
$l_user_manual_translation="Переклад підручника користувача";
$l_website_translation="Переклад сайту";
$l_upload="Upload";

$l_links="Посилання";
$l_user_progs="Програми користувачей";
$l_sponsors="Спонсори";
$l_donation="Внески";
$l_development_tools="Засоби розробки";

$l_contacts="Контакти";
$l_on_line_chat="IRC чат";
$l_forum="Форум";
$l_mailinglist="Список розсилки";
$l_guestbook="Гостьова книга";
$l_credits="Автори";

$l_misc="Різне";
$l_license="Ліцензія";
$l_sitemap="Карта сайту";

// Stats module
$l_user_online = "відвідувачів";
$l_visitors_since = "відвідувачів з 09.22.1998";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Дошка дискусій</a> з питань KDevelop, <a href=\"http://www.kde.org/\">KDE</a> та <a href=\"http://www.trolltech.com\">Qt</a>.";

// IRC module
$l_irc_description="Користувачей та розробників можна зустріти в <a href=\"chat/\">каналі <em>#kdevelop</em> на сервері <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Знімки екрану";
$l_picture_corner_description="KDevelop 3.0 в режимі IDEAl в KDE 3.2 з темою Plastik";

// User Programs module
$l_total = "ітого:";
$l_newest_entries = "нових <b>%s</b>";
$l_by = " - ";

// Downloads Per Hour module
$l_downloads_per_hour = "Кількість завантажень за годину";

// ChangeLog module
$l_change_log = "Зміни";

// Content module
$l_page_is_outdated = "<b>Ця сторінка застаріла</b>, існує оновлена <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">англомовна версія</a>";
$l_translation_by = "Переклад на українську: ";
$l_last_updated = "Ця сторінка була востаннє оновлена: ";
$l_website_bugs = "В разі проблем зі сайтом, звертайтеся до ";

// "Other versions" links
$l_other_versions="Інші версії";
$l_other_news="Інші новини";
$l_branches_compiling_section_at="Розділ компіляції на сторінці";
$l_bugs_section_at="Розділ помилок та побажань на сторінці";
$l_download_section_at="Розділ завантаження на сторінці";
$l_requirements_section_at="Розділ вимог на сторінці";
$l_tutorials_section_at="Розділ посібників на сторінці";

// Page titles
$l_pt_main="інтегроване середовище розробки - Початкова сторінка";
$l_pt_main_year="Новини %d";
$l_pt_versions="Випущені версії";
$l_pt_in_the_press="В пресі";
$l_pt_license="Ліцензія";
$l_pt_donate="Внески та спонсори";
$l_pt_website_translation_status="Стан перекладу сайту";
$l_pt_optional_files_translation_status="Стан перекладу сайту (необов'язкові файли)";
$l_pt_upload="Карта сайту";
$l_pt_upload="Upload";
$l_pt_current_work="Поточна робота";
$l_pt_join_the_team="Приєднуйтесь до нас!";
$l_pt_awards="Нагороди";
$l_pt_logos_banners="Логотипи та банери";
$l_pt_pic_corner="Знімки екрану";
$l_pt_splashscreens="Заставки";
$l_pt_users="Програми користувачів";
$l_pt_sponsors="Спонсори";
$l_pt_links_development="Посилання для розробників";
$l_pt_links_tools="Засоби розробки";
$l_pt_mailinglist="Список розсилки";
$l_pt_bugs="Помилки та побажання";
$l_pt_stats="статістіка веб сайту";
$l_pt_doc_technotes_index="TechNotes Index";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Архіви гостьової книги";
$l_pt_guestbook_guestbook_010203_1999="Гостьова книга січень-березень 1999";
$l_pt_guestbook_guestbook_040506_1999="Гостьова книга квітень-червень 1999";
$l_pt_guestbook_guestbook_0708_1999="Гостьова книга липень-серпень 1999";
$l_pt_guestbook_guestbook_091011_1999="Гостьова книга вересень-листопад 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Гостьова книга грудень-березень 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Гостьова книга квітень 2000 / липень 2004";
$l_pt_events="події";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Академія 2004";
$l_pt_events_akademy2006="Академія 2006";
$l_pt_1_3_kdevelop="1.x Головна інформація";
$l_pt_1_3_announce_kdevelop_1_3="1.3 анонс випуску";
$l_pt_1_3_authors="1.x Автори";
$l_pt_1_3_changes="1.x Зміни";
$l_pt_1_3_features="1.x Можливості";
$l_pt_1_3_pressrelease1_0="1.0 анонс випуску";
$l_pt_1_3_pressrelease1_1="1.1 анонс випуску";
$l_pt_1_3_screenshots1="1.x Знімки екрану секція 1";
$l_pt_1_3_screenshots2="1.x Знімки екрану секція 2";
$l_pt_1_3_screenshots3="1.x Знімки екрану секція 3";
$l_pt_2_1_kdevelop="2.x Головна інформація";
$l_pt_2_1_announce_kdevelop_2_0="2.0 анонс випуску";
$l_pt_2_1_authors="2.x Автори";
$l_pt_2_1_changes="2.x Зміни";
$l_pt_2_1_faq="2.x FAQ";
$l_pt_2_1_features="2.x Можливості";
$l_pt_2_1_screenshots1="2.x Знімки екрану секція 1";
$l_pt_2_1_screenshots2="2.x Знімки екрану секція 2";
$l_pt_2_1_screenshots3="2.x Знімки екрану секція 3";
$l_pt_x_x_kdevelop="%s.x Головна інформація";
$l_pt_x_x_announce_kdevelop="%s анонс випуску";
$l_pt_x_x_authors="%s.x Автори";
$l_pt_x_x_branches_compiling="%s.x Гілки SVN та компіляція";
$l_pt_x_x_changes="%s.x Зміни";
$l_pt_x_x_faq="%s.x FAQ";
$l_pt_x_x_download="%s.x Завантаження";
$l_pt_x_x_features="%s.x Можливості";
$l_pt_x_x_kdevelop_po_status="%s.x стан перекладу інтерфейсу";
$l_pt_x_x_requirements="%s.x Вимоги";
$l_pt_x_x_screenshots="%s.x Знімки екрану";
$l_pt_x_x_screenshots1="%s.x Знімки екрану секція 1";
$l_pt_x_x_screenshots2="%s.x Знімки екрану секція 2";
$l_pt_x_x_screenshots3="%s.x Знімки екрану секція 3";
$l_pt_x_x_doc_tutorial_autoconf="%s.x посібник по Autoconf/Automake";
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI посібник";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia посібник";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"User defined settings\" посібник";
$l_pt_x_x_tutorials="%s.x Посібники";
$l_pt_x_x_ChangeLog="%s.x individual SVN commit logs";
$l_pt_HEAD_kdevelop="HEAD Головна інформація";
$l_pt_HEAD_authors="HEAD Автори";
$l_pt_HEAD_branches_compiling="HEAD Гілки SVN та компіляція";
$l_pt_HEAD_changes="HEAD Зміни";
$l_pt_HEAD_ChangeLog="HEAD individual SVN commit logs";
$l_pt_HEAD_faq="HEAD FAQ";
$l_pt_HEAD_download="HEAD Завантаження";
$l_pt_HEAD_features="HEAD Можливості";
$l_pt_HEAD_kdevelop_po_status="HEAD стан перекладу інтерфейсу";
$l_pt_HEAD_requirements="HEAD Вимоги";
$l_pt_HEAD_screenshots="HEAD Знімки екрану";
$l_pt_HEAD_screenshots1="HEAD Знімки екрану секція 1";
$l_pt_HEAD_screenshots2="HEAD Знімки екрану секція 2";
$l_pt_HEAD_screenshots3="HEAD Знімки екрану секція 3";
$l_pt_tutorials="Посібники";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
