<?php
// kate: encoding iso-8859-9
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'iso-8859-9';

// The php locale, LanguageCode_CountryCode
$l_locale= 'tr_TR';

$l_graphic_mode = "Grafik Modu";
$l_text_mode = "Metin Modu";

// Logo
$l_back_kdevelop_home="KDevelop ana sayfasýna dön";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Ýngilizce",
                   "ar" => "Arabic",
                   "cs" => "Çekce",
                   "de" => "Almanca",
                   "es" => "Ýspanyolca",
                   "fr" => "Fransýzca",
                   "hu" => "Hungarian",
                   "id" => "Hintçe",
                   "it" => "Ýtalyanca",
                   "nl" => "Hollandaca",
                   "pt" => "Portekizce",
                   "pt_BR" => "Brezilya Portekizcesi",
                   "pl" => "Lehce",
                   "ro" => "Romence",
                   "ru" => "Rusca",
                   "tr" => "Türkçe",
                   "uk" => "Ukraynaca",
                   "zh_CN" => "Basitleþtirilmiþ Çince");

// Google module
$l_search="Ara";

// Quick download module
$l_quick_downloads = "Hýzlý Ýndir";
$l_current_stable_version = "Mevcut kararlý sürüm";
$l_current_development_version = "Mevcut geliþtirme sürümü";

// Menu module
$l_website_navigation="Web site turu";
$l_all_versions="tüm&nbsp;sürümler";
$l_general="Genel";
$l_home="Ana sayfa";
$l_versions="Sürümler";
$l_features="Özellikler";
$l_requirements="Gereksinimler";
$l_download="Ýndir";
$l_cvs_branches_compiling="SVN dallarýný &amp; Derleme";
$l_changes="Deðiþiklikler";
$l_bugs_wishes="Bug lar &amp; istekler";

$l_documentation="Dökümanlar";
$l_user_manual="Kullanýcý klavuzu";
$l_api_documentation="API dökümanlarý";
$l_platform_api_documentation="Platform API";
$l_tutorials="Öðretici dökümanlar";
$l_faq="S.S.S";
$l_technotes="Teknik notlar";
$l_mediawiki="Wiki";

$l_presentations_graphics="Sunumlar ve Grafikler";
$l_screenshots="Ekran Görüntüleri";
$l_in_the_press="Basýnda";
$l_awards="Ödüller";
$l_logos_banners="Logolar &amp; Bannerlar";
$l_splashscreens="Açýlýþ ekran görüntüsü";
$l_events="Etkinlikler";

$l_development="Geliþtirme";
$l_join_us="Bize katýlýn!";
$l_current_work_todo_list="Mevcut çalýþma, yapýlacaklar listesi";
$l_latest_cvs_commits="En son SVN hareketleri";
$l_browse_code="Kod incele";
$l_web_cvs="Web SVN";
$l_gui_translation="GUI çeviri";
$l_user_manual_translation="Kullanýcý klavuzu çevirisi";
$l_website_translation="Web sitesi çevirisi";
$l_upload="Karþýya yükleme";

$l_links="Baðlantýlar";
$l_user_progs="Kullanýcý programlarý";
$l_sponsors="Sponsorlar";
$l_donation="Baðýþ";
$l_development_tools="Geliþtirme araçlarý";

$l_contacts="Ýletiþim adresleri";
$l_on_line_chat="Canlý sohbet";
$l_forum="Forum";
$l_mailinglist="Posta listesi";
$l_guestbook="Ziyaretçi defteri";
$l_credits="Krediler";

$l_misc="Çeþitli";
$l_license="Lisans";
$l_sitemap="Site haritasý";

// Stats module
$l_user_online = "Online kullanýcý";
$l_visitors_since = "09/22/98 den beri ziyaretçiler";

// Forum module
$l_forum_description="Kdevelop için tartýþma <a href=\"phorum5/\">formu</a>, <a href=\"http://www.kde.org/\">KDE</a> ve <a href=\"http://www.trolltech.com\">Qt</a> ile ilgili þeyler.";

// IRC module
$l_irc_description="<a href=\"chat/\"><em>irc.kde.org</em> da ki <em>#kdevelop</em> kanalýnda </a> diðer kullanýcýlar ve geliþtiriciler ile tanýþabilirsiniz.";

// Picture Corner module
$l_picture_corner="Resim köþesi";
$l_picture_corner_description="Plastik temalý KDE 3.2 de KDevelop 3.0, IDEAl modunda";

// User Programs module
$l_total = "toplam:";
$l_newest_entries = "en yeni <b>%s</b> girdiler";
$l_by = "tarafýndan";

// Downloads Per Hour module
$l_downloads_per_hour = "Saattaki indirme sayýsý";

// ChangeLog module
$l_change_log = "Deðiþiklik kayýtlarý";

// Content module
$l_page_is_outdated = "<b>Bu sayfa zaman aþýmýna uðramýþ</b>, daha yeni bir <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">ingilizce sürümü</a> mevcut";
$l_translation_by = "Türkçe çeviri ";
$l_last_updated = "Bu sayfa en son þu tarihte güncellendi: ";
$l_website_bugs = "Site ile ilgili sorunlarýnýz varsa, lütfen þu adresi kullanarak irtibata geçin ";

// "Other versions" links
$l_other_versions="Diðer sürümler";
$l_other_news="Diðer haberler";
$l_branches_compiling_section_at="Derleme bölümü þuradadýr";
$l_bugs_section_at="Buglar &amp; istekler bölümü þuradadýr";
$l_download_section_at="Ýndirme bölümü þuradadýr";
$l_requirements_section_at="Gereksinimler bölümü þuradadýr";
$l_tutorials_section_at="Öðretici dökümanlar bölümü þuradadýr";

// Page titles
$l_pt_main="bir Tümleþik Geliþtirme Ortamý - ANASAYFA";
$l_pt_main_year="%d Haberleri";
$l_pt_versions="Çýkmýþ Sürümler";
$l_pt_in_the_press="Basýnda";
$l_pt_license="Lisans";
$l_pt_donate="Baðýþ ve Sponsorluk";
$l_pt_website_translation_status="Web site çeviri durumu";
$l_pt_optional_files_translation_status="Web site çeviri durumu (isteðe baðlý dosyalar)";
$l_pt_sitemap="Web site haritasý";
$l_pt_upload="Karþýdan yükleme";
$l_pt_current_work="Mevcut çalýþma";
$l_pt_join_the_team="Bize katýlýn!";
$l_pt_awards="Ödüller";
$l_pt_logos_banners="Logolar &amp; Bannerlar";
$l_pt_pic_corner="Resim köþesi arþivi";
$l_pt_splashscreens="Açýlýþ Ekraný resimleri";
$l_pt_users="Kullanýcý programlarý";
$l_pt_sponsors="Sponsorlar";
$l_pt_links_development="Geliþtirme baðlantýlarý";
$l_pt_links_tools="Geliþtirme araçlarý";
$l_pt_mailinglist="Posta listesi";
$l_pt_bugs="Buglar &amp; Ýstekler";
$l_pt_stats="Web site istatistikleri";
$l_pt_doc_technotes_index="Teknik Notlar Ýndeksi";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Kullanýcý defteri arþivleri";
$l_pt_guestbook_guestbook_010203_1999="Kullanýcý defteri Oca/Þub/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Kullanýcý defteri Nis/May/Haz 1999";
$l_pt_guestbook_guestbook_0708_1999="Kullanýcý defteri Tem/Aðu 1999";
$l_pt_guestbook_guestbook_091011_1999="Kullanýcý defteri Eyl/Eki/Kas 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Kullanýcý defteri Ara/Oca/Þub/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Kullanýcý defteri Nis 2000 / Tem 2004";
$l_pt_events="etkinlikler";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x temel bilgi";
$l_pt_1_3_announce_kdevelop_1_3="1.3 çýkýþ duyurusu";
$l_pt_1_3_authors="1.x yazarlar";
$l_pt_1_3_changes="1.x deðiþiklikler";
$l_pt_1_3_features="1.x özellikler";
$l_pt_1_3_pressrelease1_0="1.0 basýn-yayýn";
$l_pt_1_3_pressrelease1_1="1.1 basýn-yayýn";
$l_pt_1_3_screenshots1="1.x ekran grüntüleri bölümü 1";
$l_pt_1_3_screenshots2="1.x ekran grüntüleri bölümü 2";
$l_pt_1_3_screenshots3="1.x ekran grüntüleri bölümü 3";
$l_pt_2_1_kdevelop="2.x temel bilgi";
$l_pt_2_1_announce_kdevelop_2_0="2.0 çýkýþ duyurusu";
$l_pt_2_1_authors="2.x yazarlar";
$l_pt_2_1_changes="2.x deðiþiklikler";
$l_pt_2_1_faq="2.x SSS";
$l_pt_2_1_features="2.x özellikler";
$l_pt_2_1_screenshots1="2.x ekran grüntüleri bölümü 1";
$l_pt_2_1_screenshots2="2.x ekran grüntüleri bölümü 2";
$l_pt_2_1_screenshots3="2.x ekran grüntüleri bölümü 3";
$l_pt_x_x_kdevelop="%s.x temel bilgi";
$l_pt_x_x_announce_kdevelop="%s çýkýþ duyurusu";
$l_pt_x_x_authors="%s.x yazarlar";
$l_pt_x_x_branches_compiling="%s.x SVN dallarý &amp; Derleme";
$l_pt_x_x_changes="%s.x deðiþiklikler";
$l_pt_x_x_faq="%s.x SSS";
$l_pt_x_x_download="%s.x indir";
$l_pt_x_x_features="%s.x özellikler";
$l_pt_x_x_kdevelop_po_status="%s.x GUI çeviri durumu";
$l_pt_x_x_requirements="%s.x gereksinimler";
$l_pt_x_x_screenshots="%s.x ekran grüntüleri";
$l_pt_x_x_screenshots1="%s.x ekran grüntüleri bölümü 1";
$l_pt_x_x_screenshots2="%s.x ekran grüntüleri bölümü 2";
$l_pt_x_x_screenshots3="%s.x ekran grüntüleri bölümü 3";
$l_pt_x_x_tutorials="%s.x öðretici belgeler";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Autoconf/Automake için öðretici belgeler"; 
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI belgeler";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia belgeler";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"User defined settings\" belgeler";
$l_pt_x_x_ChangeLog="%s.x individual SVN commit logs";
$l_pt_HEAD_kdevelop="HEAD temel bilgi";
$l_pt_HEAD_authors="HEAD yazarlar";
$l_pt_HEAD_branches_compiling="HEAD SVN Dallarý &amp; Derleme";
$l_pt_HEAD_changes="HEAD deðiþiklikler";
$l_pt_HEAD_ChangeLog="HEAD individual SVN commit logs";
$l_pt_HEAD_faq="HEAD SSS";
$l_pt_HEAD_download="HEAD indir";
$l_pt_HEAD_features="HEAD özellikler";
$l_pt_HEAD_kdevelop_po_status="HEAD GUI çeviri durumu";
$l_pt_HEAD_requirements="HEAD gereksinimler";
$l_pt_HEAD_screenshots="HEAD ekran grüntüleri";
$l_pt_HEAD_screenshots1="HEAD ekran grüntüleri bölümü 1";
$l_pt_HEAD_screenshots2="HEAD ekran grüntüleri bölümü 2";
$l_pt_HEAD_screenshots3="HEAD ekran grüntüleri bölümü 3";
$l_pt_tutorials="öðretici belgeler";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
