<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'ro_RO';

$l_graphic_mode = "Mod grafic";
$l_text_mode = "Mod text";

// Logo
$l_back_kdevelop_home="Înapoi la pagina principală;";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "Engleză",
                   "ar" => "Arabiă",
                   "cs" => "Cehă",
                   "de" => "Germană",
                   "es" => "Spaniolă",
                   "fr" => "Franceză",
                   "hu" => "Maghiară",
                   "id" => "Indoneziană",
                   "it" => "Italiană",
                   "nl" => "Olandeză",
                   "pt" => "Portugheză",
                   "pt_BR" => "Portugheza braziliană",
                   "pl" => "Poloneză",
                   "ro" => "Română",
                   "ru" => "Rusă",
                   "tr" => "Turcă",
                   "uk" => "Ucrainiană",
                   "zh_CN" => "Chineza simplificată");

// Google module
$l_search="Caută";

// Quick download module
$l_quick_downloads = "Descărcare Rapid";
$l_current_stable_version = "Versiunea Stabilă Curentă";
$l_current_development_version = "Versiune în Dezvoltare";

// Menu module
$l_website_navigation="Navigare Website ";
$l_all_versions="Toate&nbsp;Versiunile";
$l_general="General";
$l_home="Home";
$l_versions="Versiuni";
$l_features="Caracteristici";
$l_requirements="Cerinţe";
$l_download="Descărcare";
$l_cvs_branches_compiling="Ramuri SVN &amp; Compilare";
$l_changes="Schimbări";
$l_bugs_wishes="Buguri &amp; Sugestii";

$l_documentation="Documentaţie";
$l_user_manual="Manualul Utilizatorului";
$l_api_documentation="Documentaţie API";
$l_platform_api_documentation="API Platformă";
$l_tutorials="Tutoriale";
$l_faq="F.A.Q.";
$l_technotes="Note tehnice";
$l_mediawiki="Wiki";

$l_presentations_graphics="Prezentări şi Grafică";
$l_screenshots="Screenshot-uri";
$l_in_the_press="În Presă";
$l_awards="Premii";
$l_logos_banners="Logo-uri &amp; Banere";
$l_splashscreens="Splashscreen";
$l_events="Evenimente";

$l_development="Dezvoltare";
$l_join_us="Alaturaţi-vă nouă!";
$l_current_work_todo_list="În lucru, Lista TODO";
$l_latest_cvs_commits="Ultimele Update-uri SVN";
$l_browse_code="Navigare prin Cod";
$l_web_cvs="Web SVN";
$l_gui_translation="Traducere GUI";
$l_user_manual_translation="Traducere Manual pentru Utilizatori";
$l_website_translation="Traducere Website";
$l_upload="Upload";

$l_links="Conexiuni";
$l_user_progs="Program Utilizatori";
$l_sponsors="Sponsori";
$l_donation="Donaţii";
$l_development_tools="Unelte pentru Dezvoltare";

$l_contacts="Contacte";
$l_on_line_chat="Discuţii On-line ";
$l_forum="Forum";
$l_mailinglist="Lista de Email";
$l_guestbook="Carte pentru Vizitatori";
$l_credits="Credite";

$l_misc="Diverse";
$l_license="Licenţa";
$l_sitemap="Harta site-ului";

// Stats module
$l_user_online = "Utilizatori online";
$l_visitors_since = "Vizitatori începînd cu 09/22/98";

// Forum module
$l_forum_description="<a href=\"phorum5/\">Forum</a> de discuţii pentru KDevelop, <a href=\"http://www.kde.org/\">KDE</a>, <a href=\"http://www.trolltech.com\">Qt</a> si subiecte adiacente.";

// IRC module
$l_irc_description="Poţi întîlni alţi utilizatori şi programatori pe canalul <a href=\"chat/\"><em>#kdevelop</em> irc la <em>irc.kde.org</em></a>.";

// Picture Corner module
$l_picture_corner="Fotografii";
$l_picture_corner_description="KDevelop 3.0 în modul IDEAl utilizînd KDE 3.2 cu tema Plastik";

// User Programs module
$l_total = "total:";
$l_newest_entries = "cele mai noi <b>%s</b> intrări";
$l_by = "de";

// Downloads Per Hour module
$l_downloads_per_hour = "Download-uri/ora";

// ChangeLog module
$l_change_log = "Jurnalul schimbărilor";

// Content module
$l_page_is_outdated = "<b>Aceasta pagina nu este actualizată</b>, o nouă <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">versiune engleza</a> există";
$l_translation_by = "Traducerea română facută de ";
$l_last_updated = "Această pagină a fost actualizată pe: ";
$l_website_bugs = "Pentru orice probleme cu privire la acest website, vă rugăm contactaţi pe ";

// "Other versions" links
$l_other_versions="Alte versiuni";
$l_other_news="Alte noutăţi";
$l_branches_compiling_section_at="Secţiune compilare la";
$l_bugs_section_at="Bug-uri &amp; recomandări la";
$l_download_section_at="Secţiune Download la";
$l_requirements_section_at="Secţiunea Cerinţe la";
$l_tutorials_section_at="Secţiunea pentru Tutoriale la";

// Page titles
$l_pt_main="un Mediu Integrat de Dezvolatare - Homepage";
$l_pt_main_year="Ştiri din %d";
$l_pt_versions="Versiuni distribuite";
$l_pt_in_the_press="În Presă";
$l_pt_license="Licenţă";
$l_pt_donate="Donaţii si Sponsorizări";
$l_pt_website_translation_status="Stadiul actual al traducerii site-ului Web";
$l_pt_optional_files_translation_status="Stadiul actual al traducerii site-ului Web";
$l_pt_sitemap="Harta site web (sitemap)";
$l_pt_upload="Upload";
$l_pt_current_work="În lucru";
$l_pt_join_the_team="Alătură-te nouă!";
$l_pt_awards="Premii";
$l_pt_logos_banners="Logo şi bannere";
$l_pt_pic_corner="Arhiva Foto";
$l_pt_splashscreens="Ecrane de pornire";
$l_pt_users="Programe utilizatori";
$l_pt_sponsors="Sponsori";
$l_pt_links_development="Linkuri pentru Dezvoltare";
$l_pt_links_tools="Unelte pentru Dezvoltare";
$l_pt_mailinglist="Lista de Email";
$l_pt_bugs="Buguri şi Dorinţe";
$l_pt_stats="Statistici ale site-ului Web";
$l_pt_doc_technotes_index="Index al notelor tehnice";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="Arhiva cărţii de vizitatori";
$l_pt_guestbook_guestbook_010203_1999="Carte de vizitatori Ian/Feb/Mar 1999";
$l_pt_guestbook_guestbook_040506_1999="Carte de vizitatori Apr/Mai/Jun 1999";
$l_pt_guestbook_guestbook_0708_1999="Carte de vizitatori Iul/Aug 1999";
$l_pt_guestbook_guestbook_091011_1999="Carte de vizitatori Sep/Oct/Noi 1999";
$l_pt_guestbook_guestbook_12_03_1999_2000="Carte de vizitatori Dec/Ian/Feb/Mar 1999/2000";
$l_pt_guestbook_guestbook_2000_2004="Carte de vizitatori Apr 2000 / Jul 2004";
$l_pt_events="evenimente";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x informaţii esenţiale";
$l_pt_1_3_announce_kdevelop_1_3="1.3 anunţ release";
$l_pt_1_3_authors="1.x autori";
$l_pt_1_3_changes="1.x schimbări";
$l_pt_1_3_features="1.x caracteristice";
$l_pt_1_3_pressrelease1_0="1.0 anunţ În presă";
$l_pt_1_3_pressrelease1_1="1.1 anunţ În presă";
$l_pt_1_3_screenshots1="1.x secţiunea 1 screenshots";
$l_pt_1_3_screenshots2="1.x secţiunea 2 screenshots";
$l_pt_1_3_screenshots3="1.x secţiunea 3 screenshots";
$l_pt_2_1_kdevelop="2.x informaţie esentială";
$l_pt_2_1_announce_kdevelop_2_0="2.0 anunţ release";
$l_pt_2_1_authors="2.x autori";
$l_pt_2_1_changes="2.x schimbări";
$l_pt_2_1_faq="2.x FAQ";
$l_pt_2_1_features="2.x caracteristici";
$l_pt_2_1_screenshots1="2.x secţiunea 1 screenshots";
$l_pt_2_1_screenshots2="2.x secţiunea 2 screenshots";
$l_pt_2_1_screenshots3="2.x secţiunea 3 screenshots";
$l_pt_x_x_kdevelop="%s.x informaţie esenţială";
$l_pt_x_x_announce_kdevelop="%s anunţ release";
$l_pt_x_x_authors="%s.x autori";
$l_pt_x_x_branches_compiling="%s.x Ramuri SVN şi Compilare";
$l_pt_x_x_changes="%s.x modificări";
$l_pt_x_x_faq="%s.x FAQ";
$l_pt_x_x_download="%s.x download";
$l_pt_x_x_features="%s.x caracteristici";
$l_pt_x_x_kdevelop_po_status="%s.x situaţie actuală la traducerea GUI";
$l_pt_x_x_requirements="%s.x cerinţe";
$l_pt_x_x_screenshots="%s.x screenshots";
$l_pt_x_x_screenshots1="%s.x secţiunea 1 screenshots";
$l_pt_x_x_screenshots2="%s.x secţiunea 2 screenshots";
$l_pt_x_x_screenshots3="%s.x secţiunea 3 screenshots";
$l_pt_x_x_tutorials="%s.x tutoriale";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Tutorial pentru Autoconf/Automake";
$l_pt_x_x_doc_kmditutorial_index="%s.x Tutorial KMDI";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Tutorial Qtopia";
$l_pt_x_x_doc_tutorial_settings_index="%s.x Tutorial \"Setări definite de utilizator\"";
$l_pt_x_x_ChangeLog="%s.x Jurnalul de modificări individuale în SVN";
$l_pt_HEAD_kdevelop="informaţie esenţială ramura HEAD";
$l_pt_HEAD_authors="Autori HEAD";
$l_pt_HEAD_branches_compiling="Ramuri SVN şi compilare HEAD";
$l_pt_HEAD_changes="Schimbări în ramura HEAD";
$l_pt_HEAD_ChangeLog="Jurnalul de modificări individuale în SVN pe ramura HEAD";
$l_pt_HEAD_faq="Întrebări frecvente pentru ramura HEAD";
$l_pt_HEAD_download="Descărcare ramura HEAD";
$l_pt_HEAD_features="Caracteristici ramura HEAD";
$l_pt_HEAD_kdevelop_po_status="Situaţia traducerii GUI în ramura HEAD";
$l_pt_HEAD_requirements="Cerinţe HEAD";
$l_pt_HEAD_screenshots="Screenshot-uri HEAD";
$l_pt_HEAD_screenshots1="Screenshot-uri HEAD secţiunea 1";
$l_pt_HEAD_screenshots2="Screenshot-uri HEAD secţiunea 2";
$l_pt_HEAD_screenshots3="Screenshot-uri HEAD secţiunea 3";
$l_pt_tutorials="tutoriale pentru";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
