<?php
// kate: encoding utf-8
// Do not translate the comments.
// Translate only the strings.

// The prefered encoding is UTF8, but you can use other ones
$l_charset_encoding= 'utf-8';

// The php locale, LanguageCode_CountryCode
$l_locale= 'zh_CN';

$l_graphic_mode = "图形模式";
$l_text_mode = "文本模式";

// Logo
$l_back_kdevelop_home="回到 KDevelop 主页";

// Named languages associative array (for the flags, translated languages, etc)
global $languages;
$languages = array("en" => "英语",
                   "ar" => "阿拉伯",
                   "cs" => "捷克",
                   "de" => "德语",
                   "es" => "西班牙语",
                   "fr" => "法语",
                   "hu" => "匈牙利语",
                   "id" => "印度尼西亚语",
                   "it" => "意大利语",
                   "nl" => "荷兰",
                   "pt" => "葡萄牙语",
                   "pt_BR" => "巴西葡萄牙语",
                   "pl" => "波兰语",
                   "ro" => "罗马尼亚语",
                   "ru" => "俄语",
                   "tr" => "土耳其语",
                   "uk" => "乌克兰语",
                   "zh_CN" => "简体中文");
// Google module
$l_search="搜索";

// Quick download module
$l_quick_downloads = "快速下载";
$l_current_stable_version = "当前稳定版本";
$l_current_development_version = "当前开发版本";

// Menu module
$l_website_navigation="网站导航";
$l_all_versions="所有版本";
$l_general="概要";
$l_home="主页";
$l_versions="版本";
$l_features="特色";
$l_requirements="依赖";
$l_download="下载";
$l_cvs_branches_compiling="SVN 分支和编译";
$l_changes="变动";
$l_bugs_wishes="缺陷和需求";

$l_documentation="文档";
$l_user_manual="用户手册";
$l_api_documentation="API 文档";
$l_platform_api_documentation="平台 API";
$l_tutorials="入门";
$l_faq="常见问题";
$l_technotes="知识库";
$l_mediawiki="Wiki";

$l_presentations_graphics="演示和图片";
$l_screenshots="截屏";
$l_in_the_press="媒体";
$l_awards="奖项";
$l_logos_banners="图标和旗标";
$l_splashscreens="溅屏";
$l_events="事件";

$l_development="开发";
$l_join_us="加入我们!";
$l_current_work_todo_list="当前的工作，TODO列表";
$l_latest_cvs_commits="最新的 SVN 提交";
$l_browse_code="浏览代码";
$l_web_cvs="Web SVN";
$l_gui_translation="GUI翻译";
$l_user_manual_translation="用户手册翻译";
$l_website_translation="网站翻译";
$l_upload="上传";

$l_links="链接";
$l_user_progs = "用户程序";
$l_sponsors="资助";
$l_donation="捐助";
$l_development_tools="开发工具";

$l_contacts="联系";
$l_on_line_chat="在线聊天";
$l_forum="论坛";
$l_mailinglist="邮件列表";
$l_guestbook="留言簿";
$l_credits="感谢";

$l_misc="其他";
$l_license="许可证";
$l_sitemap="站点地图";

// Stats module
$l_user_online = "在线用户";
$l_visitors_since = "自09/22/98共有用户";

// Forum module
$l_forum_description="KDevelop的 <a href=\"phorum5/\">讨论板</a> , <a href=\"http://www.kde.org/\">KDE</a> 和 <a href=\"http://www.trolltech.com\">Qt</a> 相关内容 .";

// IRC module
$l_irc_description="你可以在 <a href=\"chat/\"><em>irc.kde.org</em> 上的 <em>#kdevelop</em> 频道 </a> 遇到其他用户和开发人员 .";

// Picture Corner module
$l_picture_corner="图片角";
$l_picture_corner_description="IDEAl模式下的KDevelop 3.0，KDE 3.2采用Plastik主题";

// User Programs module
$l_total = "共:";
$l_newest_entries = "最新 <b>%s</b> 条目";
$l_by = "by";

// Downloads Per Hour module
$l_downloads_per_hour = "每小时下载";

// ChangeLog module
$l_change_log = "变动日志";

// Content module
$l_page_is_outdated = "<b>本页已经过期</b>，新的 <a href=\"index.html?filename=$filename&amp;set_lang=en\" hreflang=\"en\">英文版</a> 在这里";
$l_translation_by = "英文翻译维护人 ";
$l_last_updated = "本页最后更新于: ";
$l_website_bugs = "关于网站的任何问题，请联系";

// "Other versions" links
$l_other_versions="其他版本";
$l_other_news="其他新闻";
$l_branches_compiling_section_at="编译部分在";
$l_bugs_section_at="缺陷和需求部分在";
$l_download_section_at="下载部分在";
$l_requirements_section_at="依赖部分在";
$l_tutorials_section_at="入门部分在";

// Page titles
$l_pt_main="一个集成开发环境 - 主页";
$l_pt_main_year="%d的新闻";
$l_pt_versions="发布的版本";
$l_pt_in_the_press="媒体";
$l_pt_license="许可证";
$l_pt_donate="捐助和资助";
$l_pt_website_translation_status="网站翻译状态";
$l_pt_optional_files_translation_status="网站翻译状态(可选文件)";
$l_pt_sitemap="网站地图";
$l_pt_upload="上传";
$l_pt_current_work="当前的工作";
$l_pt_join_the_team="加入我们!";
$l_pt_awards="奖项";
$l_pt_logos_banners="图标和旗标";
$l_pt_pic_corner="图片角存档";
$l_pt_splashscreens="溅屏";
$l_pt_users="用户程序";
$l_pt_sponsors="资助";
$l_pt_links_development="开发链接";
$l_pt_links_tools="开发工具";
$l_pt_mailinglist="邮件列表";
$l_pt_bugs="缺陷和需求";
$l_pt_stats="网站统计";
$l_pt_doc_technotes_index="技术摘要 索引";
$l_pt_mediawiki_=$l_mediawiki;
$l_pt_chat_=$l_on_line_chat;
$l_pt_phorum5_=$l_forum;
$l_pt_guestbook_guestbook="留言簿存档";
$l_pt_guestbook_guestbook_010203_1999="1999年1/2/3月留言簿";
$l_pt_guestbook_guestbook_040506_1999="1999年/5/6月留言簿";
$l_pt_guestbook_guestbook_0708_1999="1999年7/8月留言簿";
$l_pt_guestbook_guestbook_091011_1999="1999年9/10/11月留言簿";
$l_pt_guestbook_guestbook_12_03_1999_2000="1999/2000年12/1/2/3月留言簿";
$l_pt_guestbook_guestbook_2000_2004="2000年4月至2004年7月留言簿";
$l_pt_events="事件";
$l_pt_events_linuxtag2000="Linuxtag 2000";
$l_pt_events_linuxtag2001="Linuxtag 2001";
$l_pt_events_kastle2003="Kastle 2003";
$l_pt_events_akademy2004="Akademy 2004";
$l_pt_events_akademy2006="Akademy 2006";
$l_pt_1_3_kdevelop="1.x 主信息页";
$l_pt_1_3_announce_kdevelop_1_3="1.3 发布公告";
$l_pt_1_3_authors="1.x 作者";
$l_pt_1_3_changes="1.x 变动";
$l_pt_1_3_features="1.x 特色";
$l_pt_1_3_pressrelease1_0="1.0 公告发布";
$l_pt_1_3_pressrelease1_1="1.1 公告发布";
$l_pt_1_3_screenshots1="1.x 截屏 1";
$l_pt_1_3_screenshots2="1.x 截屏 2";
$l_pt_1_3_screenshots3="1.x 截屏 3";
$l_pt_2_1_kdevelop="2.x 主信息页";
$l_pt_2_1_announce_kdevelop_2_0="2.0 发布公告";
$l_pt_2_1_authors="2.x 作者";
$l_pt_2_1_changes="2.x 变动";
$l_pt_2_1_faq="2.x 常见问题";
$l_pt_2_1_features="2.x 特色";
$l_pt_2_1_screenshots1="2.x 截屏 1";
$l_pt_2_1_screenshots2="2.x 截屏 2";
$l_pt_2_1_screenshots3="2.x 截屏 3";
$l_pt_x_x_kdevelop="%s.x 主信息页";
$l_pt_x_x_announce_kdevelop="%s 发布公告";
$l_pt_x_x_authors="%s.x 作者";
$l_pt_x_x_branches_compiling="%s.x SVN 分支和编译";
$l_pt_x_x_changes="%s.x 变动";
$l_pt_x_x_faq="%s.x 常见问题";
$l_pt_x_x_download="%s.x 下载";
$l_pt_x_x_features="%s.x 特色";
$l_pt_x_x_kdevelop_po_status="%s.x GUI 翻译状态";
$l_pt_x_x_requirements="%s.x 依赖";
$l_pt_x_x_screenshots="%s.x 截";
$l_pt_x_x_screenshots1="%s.x 截屏 1";
$l_pt_x_x_screenshots2="%s.x 截屏 2";
$l_pt_x_x_screenshots3="%s.x 截屏 3";
$l_pt_x_x_tutorials="%s.x 入门";
$l_pt_x_x_doc_tutorial_autoconf="%s.x Autoconf/Automake入门"; 
$l_pt_x_x_doc_kmditutorial_index="%s.x KMDI 入门";
$l_pt_x_x_doc_tutorial_qtopia_index="%s.x Qtopia 入门";
$l_pt_x_x_doc_tutorial_settings_index="%s.x \"用户自定义设置\" 入门";
$l_pt_x_x_ChangeLog="%s.x 单独的SVN提交日志";
$l_pt_HEAD_kdevelop="HEAD 主信息页";
$l_pt_HEAD_authors="HEAD 作者";
$l_pt_HEAD_branches_compiling="HEAD SVN 分支和编译";
$l_pt_HEAD_changes="HEAD 变动";
$l_pt_HEAD_ChangeLog="HEAD 单独的SVN提交日志";
$l_pt_HEAD_faq="HEAD 常见问题";
$l_pt_HEAD_download="HEAD 下载";
$l_pt_HEAD_features="HEAD 特色";
$l_pt_HEAD_kdevelop_po_status="HEAD GUI 翻译状态";
$l_pt_HEAD_requirements="HEAD 依赖";
$l_pt_HEAD_screenshots="HEAD 截";
$l_pt_HEAD_screenshots1="HEAD 截屏 1";
$l_pt_HEAD_screenshots2="HEAD 截屏 2";
$l_pt_HEAD_screenshots3="HEAD 截屏 3";
$l_pt_tutorials="入门";
$l_pt_HEAD_doc_api_=$l_api_documentation;
$l_pt_HEAD_doc_platform_=$l_platform_api_documentation;
$HEAD_user_manual_url='http://docs.kde.org/development/en/kdevelop/kdevelop/';
